// SPDX-License-Identifier: Apache-2.0
import assert from "node:assert/strict";
import test from "node:test";
import { AdvisoryReceiptAssuranceError, evaluateAdvisoryReceiptPrivateState, persistAdvisoryReceipt } from "./advisory-receipt-assurance.mjs";
import { evaluateWindowsPrivateState } from "./windows-private-state.mjs";
const OWNER = "S-1-5-21-concrete-owner";
const secureWindows = () => ({ platform: "windows", expectedOwner: OWNER, file: { kind: "file", owner: OWNER, reparsePoint: false, dacl: { status: "secure", principals: [OWNER] } }, directory: { kind: "directory", owner: OWNER, reparsePoint: false, dacl: { status: "secure", principals: [OWNER] } } });
function memoryIo({ directorySync = null, readback = null, failWrite = null } = {}) { const files = new Map(); const events = []; return { files, events, writeFileSync(path, bytes) { events.push(`write:${path}`); if (failWrite) throw failWrite; files.set(path, Buffer.from(bytes)); }, openSync(path) { events.push(`open:${path}`); return path; }, fsyncSync(fd) { events.push(`fsync:${fd}`); }, closeSync(fd) { events.push(`close:${fd}`); }, renameSync(from, to) { events.push(`rename:${from}:${to}`); files.set(to, files.get(from)); files.delete(from); }, fsyncDirectory(path) { events.push(`dirsync:${path}`); if (directorySync) throw directorySync; }, readFileSync(path) { events.push(`read:${path}`); return readback ?? files.get(path); }, unlinkSync(path) { events.push(`unlink:${path}`); files.delete(path); } }; }
const assured = { assess: () => ({ status: "secure" }) }; const target = "/private/receipt.json";
test("Windows evidence separately requires concrete owner, DACL and reparse-point safety", () => { assert.equal(evaluateAdvisoryReceiptPrivateState(secureWindows()).status, "secure"); for (const principal of ["Everyone", "Users", "Authenticated Users", "SYSTEM", "Administrators"]) { const evidence = secureWindows(); evidence.file.dacl.principals.push(principal); assert.equal(evaluateAdvisoryReceiptPrivateState(evidence).status, "insecure", principal); } const reparse = secureWindows(); reparse.directory.reparsePoint = true; assert.equal(evaluateAdvisoryReceiptPrivateState(reparse).status, "insecure"); const foreignOwner = secureWindows(); foreignOwner.file.owner = "SYSTEM"; assert.equal(evaluateAdvisoryReceiptPrivateState(foreignOwner).status, "insecure"); const unavailable = secureWindows(); unavailable.file.dacl = { status: "unavailable" }; assert.equal(evaluateAdvisoryReceiptPrivateState(unavailable).status, "unavailable"); const unsupported = secureWindows(); unsupported.file.dacl = { status: "unsupported" }; assert.equal(evaluateAdvisoryReceiptPrivateState(unsupported).status, "unsupported"); });
test("macOS retains the POSIX owner, mode, and reparse-point contract", () => { const secure = { platform: "darwin", expectedOwner: OWNER, file: { kind: "file", owner: OWNER, reparsePoint: false, mode: 0o600 }, directory: { kind: "directory", owner: OWNER, reparsePoint: false, mode: 0o700 } }; assert.equal(evaluateAdvisoryReceiptPrivateState(secure).status, "secure"); secure.file.mode = 0o640; assert.equal(evaluateAdvisoryReceiptPrivateState(secure).status, "insecure"); });
test("native Windows boundary permits only the concrete owner DACL", () => { const secure = { currentOwner: "DESKTOP\\agent", owner: "DESKTOP\\agent", reparsePoint: false, principals: ["DESKTOP\\agent"] }; assert.equal(evaluateWindowsPrivateState(secure).status, "secure"); for (const principal of ["SYSTEM", "BUILTIN\\Administrators", "Everyone", "DESKTOP\\other"]) { assert.equal(evaluateWindowsPrivateState({ ...secure, principals: [...secure.principals, principal] }).status, "insecure"); } assert.equal(evaluateWindowsPrivateState({ ...secure, reparsePoint: true }).status, "insecure"); assert.equal(evaluateWindowsPrivateState(null).status, "unavailable"); });
test("persistence confirms exact readback bytes only after rename and directory durability", () => { const io = memoryIo(); const bytes = Buffer.from('{"receipt":true}\n'); const result = persistAdvisoryReceipt({ target, bytes, assurance: assured, io, temporaryName: ".receipt.tmp" }); assert.equal(result.status, "durable"); assert.deepEqual(result.bytes, bytes); assert.deepEqual(io.events, ["write:/private/.receipt.tmp", "open:/private/.receipt.tmp", "fsync:/private/.receipt.tmp", "close:/private/.receipt.tmp", "rename:/private/.receipt.tmp:/private/receipt.json", "dirsync:/private", "read:/private/receipt.json"]); });
test("pre-rename failures clean the temporary bytes and never publish a receipt", () => { const io = memoryIo({ failWrite: Object.assign(new Error("disk"), { code: "EIO" }) }); assert.throws(() => persistAdvisoryReceipt({ target, bytes: Buffer.from("x"), assurance: assured, io, temporaryName: ".pre.tmp" }), (error) => error instanceof AdvisoryReceiptAssuranceError && error.status === "pre_rename_failure"); assert.equal(io.files.has(target), false); assert.equal(io.events.includes("rename:/private/.pre.tmp:/private/receipt.json"), false); });
test("post-rename unsupported and unknown directory durability are typed non-successes with recovery bytes", () => { for (const [code, expected, platform] of [["ENOTSUP", "unsupported", "posix"], ["EIO", "durability_unknown", "posix"], ["EPERM", "unsupported", "windows"], ["EPERM", "durability_unknown", "posix"], ["EINVAL", "unsupported", "darwin"]]) { const io = memoryIo({ directorySync: Object.assign(new Error(code), { code }) }); const bytes = Buffer.from(`${platform}-${code}`); assert.throws(() => persistAdvisoryReceipt({ target, bytes, assurance: assured, io, temporaryName: `.${platform}-${code}.tmp`, platform }), (error) => error instanceof AdvisoryReceiptAssuranceError && error.status === expected && error.phase === "post-rename-directory-sync"); assert.deepEqual(io.files.get(target), bytes, `${platform}/${code} retains only the recovery state after rename`); assert.equal(io.events.some((event) => event.startsWith("read:")), false, `${platform}/${code} is not usable/read back as a receipt`); } });
