#!/usr/bin/env node
// SPDX-License-Identifier: SUL-1.0
import assert from "node:assert/strict";
import { admitCredentialLeaseUse, createAssumptionSet, createCredentialLease, evaluateLeaseAssumptions, revokeSyntheticCredentialLease, validateCredentialLease } from "./credential-lease.mjs";
const A="a".repeat(64),B="b".repeat(64);let n=0;const check=(name,fn)=>{fn();n++;console.log(`PASS CLS${String(n).padStart(2,"0")} ${name}`);};
const assumptions=createAssumptionSet({assumptionSetId:"set",subjectSha256:A,assumptions:[{name:"scope",value:"synthetic",source:"test"}],issuedBy:"test",issuedAt:0,expiresAt:100,stopConditions:["authority-drift"],escalation:"po-gate",forbiddenAuthorities:["approval","credential-issuance","delegation","external-mutation","merge","release"]});
const lease=(issuedAt=0,expiresAt=200,disposition="paused")=>createCredentialLease({leaseId:"lease",broker:"fake",subjectSha256:A,repository:B,operations:["read"],targets:[A],issuedAt,expiresAt,revocationHandleSha256:B,credentialClass:{kind:"synthetic",assumptions,assumptionDisposition:disposition},status:"active",readbackSha256:B});
check("creates a closed exact-root, secret-free active lease",()=>{assert.equal(validateCredentialLease(lease()).ok,true);assert.throws(()=>lease(-1),/BOUND:lease/);assert.throws(()=>lease(10,10),/BOUND:lease/);assert.equal(JSON.stringify(lease()).includes("secret"),false);assert.deepEqual(Object.keys(lease()).sort(),["broker","credentialClass","expiresAt","issuedAt","leaseId","operations","readbackSha256","recordSha256","repository","revocationHandleSha256","schema","status","subjectSha256","targets"]);});
check("admits only an active lease within its issued interval and exact scope",()=>{const use={subjectSha256:A,repository:B,operations:["read"],targets:[A],atMs:1};assert.equal(admitCredentialLeaseUse(lease(),use).ok,true);assert.equal(admitCredentialLeaseUse(lease(),{...use,atMs:-1}).code,"SHAPE:lease-use");assert.equal(admitCredentialLeaseUse(lease(10),use).code,"UNAVAILABLE:lease");assert.equal(admitCredentialLeaseUse(lease(),{...use,operations:["write"]}).code,"AUTHORITY:lease-scope");assert.equal(admitCredentialLeaseUse(lease(),{...use,atMs:200}).code,"UNAVAILABLE:lease");});
check("binds assumption disposition in the admitted lease",()=>{assert.equal(evaluateLeaseAssumptions(lease(0,200,"failed"),{atMs:1,observedStopConditions:["authority-drift"],expiryDisposition:"paused"}).disposition,"failed");assert.equal(evaluateLeaseAssumptions(lease(),{atMs:100,observedStopConditions:[]}).disposition,"paused");});
check("revokes deterministically and denies unrelated repository, credential, home, SSH and global-Git canaries",()=>{for(const reason of ["success","failure","cancellation","timeout","recovery"]){const revoked=revokeSyntheticCredentialLease(lease(),reason).lease;assert.equal(revoked.status,"revoked");assert.equal(validateCredentialLease(revoked).ok,true);}for(const operation of ["read-other-repository","read-credential","read-home","read-ssh","read-global-git"])assert.equal(admitCredentialLeaseUse(lease(),{subjectSha256:A,repository:B,operations:[operation],targets:[A],atMs:1}).code,"AUTHORITY:lease-scope");});
console.log(`${n}/4 checks passed.`);
