// SPDX-License-Identifier: SUL-1.0
/** Pure B2-C secret-free credential lease validator and synthetic revocation reducer. */
import { createHash } from "node:crypto";
export const CREDENTIAL_LEASE_SCHEMA="pipeline.credential-lease.v1";
const SHA=/^[a-f0-9]{64}$/u, ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/u;
const exact=(v,keys)=>v!==null&&typeof v==="object"&&!Array.isArray(v)&&Object.keys(v).length===keys.length&&keys.every((key)=>Object.hasOwn(v,key)); const clone=(v)=>structuredClone(v); function freeze(v){if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.values(v).forEach(freeze);Object.freeze(v);}return v;} const sorted=(v,p)=>Array.isArray(v)&&v.length<=256&&v.every(p)&&v.every((x,i)=>i===0||JSON.stringify(v[i-1])<JSON.stringify(x));
export function canonicalCredentialLeaseJson(v){if(Array.isArray(v))return`[${v.map(canonicalCredentialLeaseJson).join(",")}]`;if(v&&typeof v==="object")return`{${Object.keys(v).sort().map((k)=>`${JSON.stringify(k)}:${canonicalCredentialLeaseJson(v[k])}`).join(",")}}`;return JSON.stringify(v);} const hash=(v)=>createHash("sha256").update(`${CREDENTIAL_LEASE_SCHEMA}\0${canonicalCredentialLeaseJson(v)}`,"utf8").digest("hex");
const assumption=(v,digest=true)=>exact(v,["assumptionSetId","subjectSha256","assumptions","issuedBy","issuedAt","expiresAt","stopConditions","escalation","forbiddenAuthorities","recordSha256"])&&ID.test(v.assumptionSetId)&&SHA.test(v.subjectSha256)&&sorted(v.assumptions,(x)=>exact(x,["name","value","source"])&&[x.name,x.value,x.source].every((y)=>typeof y==="string"&&y.length>0&&y.length<=256))&&ID.test(v.issuedBy)&&Number.isSafeInteger(v.issuedAt)&&Number.isSafeInteger(v.expiresAt)&&v.expiresAt>v.issuedAt&&sorted(v.stopConditions,(x)=>ID.test(x))&&ID.test(v.escalation)&&sorted(v.forbiddenAuthorities,(x)=>["delegation","approval","credential-issuance","external-mutation","merge","release"].includes(x))&&v.forbiddenAuthorities.length===6&&SHA.test(v.recordSha256)&&(!digest||assumptionDigest(v)===v.recordSha256);
export function assumptionDigest(v){const{recordSha256,...body}=v??{};return hash(body);} export function createAssumptionSet(input){const v={...clone(input),recordSha256:"0".repeat(64)};if(Object.hasOwn(input,"recordSha256")||!assumption(v,false))throw new Error("SHAPE:assumption-set");v.recordSha256=assumptionDigest(v);return freeze(v);}
const credentialClass=(v)=>exact(v,["kind","assumptions","assumptionDisposition"])&&ID.test(v.kind)&&assumption(v.assumptions)&&["paused","failed"].includes(v.assumptionDisposition);
function code(v,digest=true){if(!exact(v,["schema","leaseId","broker","subjectSha256","repository","operations","targets","issuedAt","expiresAt","revocationHandleSha256","credentialClass","status","readbackSha256","recordSha256"]))return"SHAPE:lease";if(v.schema!==CREDENTIAL_LEASE_SCHEMA)return"SCHEMA:lease";if(![v.leaseId,v.broker].every((x)=>ID.test(x))||![v.subjectSha256,v.repository,v.revocationHandleSha256,v.readbackSha256,v.recordSha256].every((x)=>SHA.test(x))||!sorted(v.operations,(x)=>ID.test(x))||v.operations.length===0||!sorted(v.targets,(x)=>SHA.test(x))||v.targets.length===0||!Number.isSafeInteger(v.issuedAt)||v.issuedAt<0||!Number.isSafeInteger(v.expiresAt)||v.expiresAt<0||v.expiresAt<=v.issuedAt||!credentialClass(v.credentialClass)||!["issued","active","revoked","expired","unknown"].includes(v.status)||(digest&&leaseDigest(v)!==v.recordSha256))return"BOUND:lease";return null;}
export function leaseDigest(v){const{recordSha256,...body}=v??{};return hash(body);} export function validateCredentialLease(v){const c=code(v);return c?{ok:false,code:c}:{ok:true,code:null};} export function createCredentialLease(input){const v={schema:CREDENTIAL_LEASE_SCHEMA,...clone(input),recordSha256:"0".repeat(64)};if(Object.hasOwn(input,"schema")||Object.hasOwn(input,"recordSha256")||code(v,false))throw new Error(code(v,false)??"SHAPE:lease-input");v.recordSha256=leaseDigest(v);return freeze(v);}
const leaseUseCode=(request)=>!exact(request,["subjectSha256","repository","operations","targets","atMs"])||![request.subjectSha256,request.repository].every((x)=>SHA.test(x))||!sorted(request.operations,(x)=>ID.test(x))||!sorted(request.targets,(x)=>SHA.test(x))||!Number.isSafeInteger(request.atMs)||request.atMs<0?"SHAPE:lease-use":null;
export function validateCredentialLeaseUse(request){const c=leaseUseCode(request);return c?{ok:false,code:c}:{ok:true,code:null};}
export function admitCredentialLeaseUse(lease,request){if(code(lease))return{ok:false,code:"SHAPE:lease"};const shape=validateCredentialLeaseUse(request);if(!shape.ok)return shape;if(lease.status!=="active"||request.atMs<lease.issuedAt||request.atMs>=lease.expiresAt)return{ok:false,code:"UNAVAILABLE:lease"};if(request.subjectSha256!==lease.subjectSha256||request.repository!==lease.repository||request.subjectSha256!==lease.credentialClass.assumptions.subjectSha256||request.operations.some((x)=>!lease.operations.includes(x))||request.targets.some((x)=>!lease.targets.includes(x)))return{ok:false,code:"AUTHORITY:lease-scope"};return{ok:true,code:"LEASE:admitted"};}
export function evaluateLeaseAssumptions(lease,{atMs,observedStopConditions}){if(code(lease)||!Number.isSafeInteger(atMs)||atMs<0||!sorted(observedStopConditions,(x)=>ID.test(x)))return{ok:false,code:"SHAPE:assumption-control",disposition:null};const assumptions=lease.credentialClass.assumptions;if(atMs>=assumptions.expiresAt)return{ok:true,code:"ASSUMPTION:expired",disposition:lease.credentialClass.assumptionDisposition};if(observedStopConditions.some((x)=>assumptions.stopConditions.includes(x)))return{ok:true,code:"ASSUMPTION:stopped",disposition:lease.credentialClass.assumptionDisposition};return{ok:true,code:"ASSUMPTION:active",disposition:null};}
export function revokeSyntheticCredentialLease(lease,reason){if(code(lease))throw new Error("SHAPE:lease");if(!["success","failure","cancellation","timeout","recovery"].includes(reason))return{ok:false,code:"SHAPE:revocation",lease:null};const next={...clone(lease),status:"revoked",recordSha256:"0".repeat(64)};next.recordSha256=leaseDigest(next);return{ok:true,code:"LEASE:revoked",lease:freeze(next)};}
