// SPDX-License-Identifier: SUL-1.0
/** Actual filesystem budget tests; sealed observers below are controlled host stubs, not native execution. */
import { registerTestCaseCompletion } from "./test-case-completion.mjs";
import { openSync as openCompletionDescriptor } from "node:fs";

const completionCases = [];
function test(name, run) {
  if (arguments.length !== 2 || typeof run !== "function") throw new TypeError("Required completion expects the preserved two-argument test registration");
  completionCases.push({ id: "RC08C" + String(completionCases.length + 1).padStart(3, "0"), name, run });
}
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,writeFileSync,rmSync,readdirSync,chmodSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createInitialAdvisorContext,designAdvisorValueSha256,designAdvisorBytesSha256,SOURCE_NAMES} from './design-advisor-course.mjs';
import {createDesignAdvisorCourseStore,designAdvisorRouteSlots,readExistingDesignAdvisorCourse} from './design-advisor-course-store.mjs';
const H='1'.repeat(64),DATE='2026-09-28T00:00:00.000Z';
function context(){const sourceBytes=Object.fromEntries(SOURCE_NAMES.map(n=>[n,Buffer.from(`${n}: controlled bytes\n`)])),sources=Object.fromEntries(SOURCE_NAMES.map(n=>[n,{path:`specs/feature/${n}.md`,sha256:designAdvisorBytesSha256(sourceBytes[n])}]));return createInitialAdvisorContext({repoFingerprint:H,featureId:'feature',authoringDispatchId:'author',initialCandidate:{commit:'a'.repeat(40),tree:'b'.repeat(40)},sources,sourceBytes,reason:'architecture-tradeoff',routePolicySha256:H,createdAt:DATE}).context;}
function fixture(){const common=mkdtempSync(join(process.env.PIPELINE_COURSE_TEST_BASE??tmpdir(),'advisor-course-'));const initial=context();const brands=new WeakMap(),receipts=new Map();const hostStore={readForBinding(ref,binding){const p=receipts.get(ref.id);if(!p||p.hostReceipt.sha256!==ref.sha256||designAdvisorValueSha256(p.courseBinding)!==designAdvisorValueSha256(binding.courseBinding))return {status:'unavailable',code:'HOST-UNKNOWN'};const observation=Object.freeze({});brands.set(observation,p);return observation;},project(o){if(!brands.has(o))throw Error('unbranded');return brands.get(o);}};const options={gitCommonDir:common,repoFingerprint:H,featureId:'feature',runner:'codex',observeInitialContext:c=>({status:'verified',contextSha256:designAdvisorValueSha256(c)}),observeCourseDecision:m=>({status:'approved',...m,decisionRef:'explicit-input',decisionSha256:H}),observeNoChild:m=>({courseBinding:m,outcome:'unavailable',code:'callback-unavailable',childStarted:false,inputSubmitted:false,attemptCount:0}),hostStore};const store=createDesignAdvisorCourseStore(options);return {common,initial,store,options,receipts,close:()=>rmSync(common,{recursive:true,force:true})};}
async function reserve(f){const opened=await f.store.openInitialCourse({initialContext:f.initial});assert.equal(opened.status,'available');const r=f.store.reserveCycle({courseId:opened.courseId,initialContextSha256:opened.initialContextSha256});assert.equal(r.status,'reserved');return r;}
test('persistent reservation is not reset by fresh reader, dispatch or candidate change',async()=>{const f=fixture();try{const r=await reserve(f),fresh=createDesignAdvisorCourseStore(f.options);assert.equal(fresh.reserveCycle({courseId:r.courseId,initialContextSha256:r.initialContextSha256}).status,'recovery-required');const changed=structuredClone(f.initial);changed.authoringDispatchId='another-dispatch';changed.initialCandidate.commit='c'.repeat(40);const reused=await fresh.openInitialCourse({initialContext:changed});assert.equal(reused.status,'recovery-required');assert.equal(reused.courseId,r.courseId);assert.equal(reused.initialContextSha256,r.initialContextSha256);assert.equal(fresh.reserveCycle({courseId:'dac_invented',initialContextSha256:r.initialContextSha256}).status,'refused');}finally{f.close();}});
test('one registry consult slot finalizes from branded host reader projection; later fresh reader reuses without another cycle',async()=>{const f=fixture();try{const r=await reserve(f),slot=r.slots[0],dispatch={dispatchId:'advisor',queueRevision:0,candidateCommit:f.initial.initialCandidate.commit,candidateTree:f.initial.initialCandidate.tree};assert.equal(r.slots.length,1);const a=f.store.reserveAttempt(r.token,{...slot,dispatch,requestSha256:H});assert.equal(a.status,'attempt-reserved');const hostReceipt={id:'drh_'+'2'.repeat(32),sha256:'3'.repeat(64)};f.receipts.set(hostReceipt.id,{courseBinding:a.courseBinding,outcome:'answered',initialQuestionSha256:f.initial.questionSha256,initialEvidenceSha256:f.initial.evidenceSha256,hostReceipt,advisoryReceipt:{id:'advisor',sha256:H},requestSha256:H,recipeSha256:H,answerSha256:H,reportCanonicalSha256:H,proposalSetSha256:designAdvisorValueSha256([])});assert.equal((await f.store.finalizeAttempt(r.token,{hostReceipt})).status,'attempt-finalized');assert.equal((await f.store.finalizeCycle(r.token,{hostReceipt})).status,'reuse-terminal');const fresh=createDesignAdvisorCourseStore(f.options),again=fresh.reserveCycle({courseId:r.courseId,initialContextSha256:r.initialContextSha256});assert.equal(again.status,'reuse-terminal');assert.equal(again.attempts.length,1);assert.equal(fresh.reserveAttempt(Object.freeze({}),{...slot,dispatch,requestSha256:H}).code,'DACS-RESERVATION-TOKEN');}finally{f.close();}});
test('missing or fabricated host receipt cannot finalize; reserved budget stays uncertain',async()=>{const f=fixture();try{const r=await reserve(f),slot=r.slots[0];f.store.reserveAttempt(r.token,{...slot,dispatch:{dispatchId:'advisor',queueRevision:0,candidateCommit:f.initial.initialCandidate.commit,candidateTree:f.initial.initialCandidate.tree},requestSha256:H});const result=await f.store.finalizeAttempt(r.token,{hostReceipt:{id:'drh_'+'f'.repeat(32),sha256:H}});assert.equal(result.status,'unavailable');assert.equal(createDesignAdvisorCourseStore(f.options).readCurrent().status,'recovery-required');assert.equal((await f.store.finalizeNoChild(r.token)).code,'DACS-NO-CHILD-HAS-ATTEMPT');}finally{f.close();}});
test('sealed no-child outcome consumes this course, and arbitrary JSON cannot reset or grant new course',async()=>{const f=fixture();try{const r=await reserve(f);assert.equal((await f.store.finalizeNoChild(r.token)).status,'reuse-terminal');const fresh=createDesignAdvisorCourseStore({...f.options,observeCourseDecision:null});const next=structuredClone(f.initial);next.reason='risk-review';next.questionSha256=(await import('./design-advisor-course.mjs')).hashInitialAdvisorQuestion({reason:next.reason,sources:next.sources});const missing=await fresh.openNewCourse({initialContext:next,parentCourseId:r.courseId,decision:{status:'approved'}});assert.equal(missing.status,'unavailable');assert.equal(fresh.readCurrent().courseId,r.courseId);assert.equal((await f.store.openNewCourse({initialContext:f.initial,parentCourseId:r.courseId})).code,'DACS-NO-NEW-SUBSTANTIVE-QUESTION');const created=await f.store.openNewCourse({initialContext:next,parentCourseId:r.courseId});assert.equal(created.status,'available');assert.notEqual(created.courseId,r.courseId);const successor=f.store.reserveCycle({courseId:created.courseId,initialContextSha256:created.initialContextSha256});assert.equal((await f.store.finalizeNoChild(successor.token)).status,'reuse-terminal');assert.equal((await f.store.openNewCourse({initialContext:f.initial,parentCourseId:created.courseId})).code,'DACS-OWNER-DECISION-REUSED');let decisionSeq=2,current=created;const bounded=createDesignAdvisorCourseStore({...f.options,observeCourseDecision:m=>({status:'approved',...m,decisionRef:'owner-'+(++decisionSeq),decisionSha256:designAdvisorValueSha256({decisionSeq})})});for(let n=3;n<=32;n++){const initialContext=n%2===0?next:f.initial;current=await bounded.openNewCourse({initialContext,parentCourseId:current.courseId});assert.equal(current.status,'available');const reserved=bounded.reserveCycle({courseId:current.courseId,initialContextSha256:current.initialContextSha256});assert.equal((await bounded.finalizeNoChild(reserved.token)).status,'reuse-terminal');}const inventory=readdirSync(f.common,{recursive:true}).sort();assert.equal((await bounded.openNewCourse({initialContext:f.initial,parentCourseId:current.courseId})).code,'DACS-INDEX-BOUND');assert.deepEqual(readdirSync(f.common,{recursive:true}).sort(),inventory);}finally{f.close();}});
test('oversized or permission-drifted private metadata fails before any budget reuse',async()=>{for(const kind of ['oversized','mode']){const f=fixture();try{await reserve(f);const scope=readdirSync(join(f.common,'agent-pipeline','design-advisor-courses'))[0],base=join(f.common,'agent-pipeline','design-advisor-courses',scope),index=join(base,'index-0001.json');if(kind==='oversized')writeFileSync(index,Buffer.alloc(65537));else chmodSync(index,0o644);assert.equal(f.store.readCurrent().status,'unavailable');}finally{f.close();}}});
test('corrupt linked state never turns a reserved budget into available',async()=>{const f=fixture();try{const r=await reserve(f),scope=readdirSync(join(f.common,'agent-pipeline','design-advisor-courses'))[0],path=join(f.common,'agent-pipeline','design-advisor-courses',scope,r.courseId,'state-0002.json');const value=JSON.parse(readFileSync(path));value.status='available';writeFileSync(path,JSON.stringify(value)+'\n',{mode:0o600});assert.equal(f.store.readCurrent().status,'unavailable');}finally{f.close();}});
test('hanging initial observer times out finitely and late completion does not create a course',async()=>{const f=fixture();try{let resolveObserver;const store=createDesignAdvisorCourseStore({...f.options,operationTimeoutMs:10,observeInitialContext:()=>new Promise(r=>resolveObserver=r)});const result=await store.openInitialCourse({initialContext:f.initial});assert.equal(result.status,'unavailable');assert.equal(result.code,'DACS-INITIAL-TIMEOUT');resolveObserver({status:'verified',contextSha256:designAdvisorValueSha256(f.initial)});await new Promise(r=>setTimeout(r,20));assert.equal(store.readCurrent().status,'absent');}finally{f.close();}});
test('registry controls finite route slots without opening arbitrary extra attempts',()=>{assert.equal(designAdvisorRouteSlots({runner:'codex'}).length,1);assert.equal(designAdvisorRouteSlots({runner:'antigravity'}).length,0);const claude=designAdvisorRouteSlots({runner:'claude'});assert.ok(claude.length<=4);assert.equal(claude.filter(s=>s.kind==='consult').length,1);});
test('read-only missing getter creates no store and existing getter changes no physical inventory',async()=>{const common=mkdtempSync(join(process.env.PIPELINE_COURSE_TEST_BASE??tmpdir(),'advisor-readonly-'));try{const absent=readExistingDesignAdvisorCourse({gitCommonDir:common,repoFingerprint:H,featureId:'feature'});assert.equal(absent.status,'absent');assert.deepEqual(readdirSync(common),[]);}finally{rmSync(common,{recursive:true,force:true});}const f=fixture();try{const r=await reserve(f);await f.store.finalizeNoChild(r.token);const before=readdirSync(f.common,{recursive:true}).sort();const read=readExistingDesignAdvisorCourse({gitCommonDir:f.common,repoFingerprint:H,featureId:'feature',courseId:r.courseId,initialContextSha256:r.initialContextSha256});assert.equal(read.status,'reuse-terminal');assert.equal(read.hostExecutionVerified,false);assert.equal(read.implementationAuthority,false);assert.deepEqual(readdirSync(f.common,{recursive:true}).sort(),before);}finally{f.close();}});
test('initial course needs actual initial provenance, not another human approval ceremony',async()=>{const f=fixture();try{const noExtraApproval=createDesignAdvisorCourseStore({...f.options,observeCourseDecision:null});assert.equal((await noExtraApproval.openInitialCourse({initialContext:f.initial})).status,'available');}finally{f.close();}});

// Each original sibling callback is registered individually; no envelope case.
if (completionCases.length !== 10) throw new Error("Required completion declared case count drift");
const completionFd = process.env.PIPELINE_VERIFY_CASE_COMPLETION_FD === undefined
  ? openCompletionDescriptor(process.platform === "win32" ? "NUL" : "/dev/null", "w")
  : Number(process.env.PIPELINE_VERIFY_CASE_COMPLETION_FD);
registerTestCaseCompletion({ cases: completionCases, fd: completionFd,
  maxBytes: Number(process.env.PIPELINE_VERIFY_CASE_COMPLETION_MAX_BYTES ?? "65536") });
