// SPDX-License-Identifier: SUL-1.0
import { registerTestCaseCompletion } from "./test-case-completion.mjs";
import { openSync as openCompletionDescriptor } from "node:fs";

const completionCases = [];
function test(name, run) {
  if (arguments.length !== 2 || typeof run !== "function") throw new TypeError("Required completion expects the preserved two-argument test registration");
  completionCases.push({ id: "RC09C" + String(completionCases.length + 1).padStart(3, "0"), name, run });
}
import assert from 'node:assert/strict';
import {createInitialAdvisorContext,validateInitialAdvisorContext,validateInitialToFinalBinding,buildInitialAdvisorQuestion,hashInitialAdvisorQuestion,designAdvisorValueSha256,designAdvisorBytesSha256,SOURCE_NAMES} from './design-advisor-course.mjs';
import {advisoryEvidenceBundleSha256} from './advisory-lifecycle-v2.mjs';
import { devNull } from 'node:os';
const H='1'.repeat(64),I={commit:'a'.repeat(40),tree:'b'.repeat(40)},F={commit:'c'.repeat(40),tree:'d'.repeat(40)},DATE='2026-09-28T00:00:00.000Z';
function fixture(){const sourceBytes=Object.fromEntries(SOURCE_NAMES.map(n=>[n,Buffer.from(`${n}: Ä\r\ncontrolled initial bytes\n`)])),sources=Object.fromEntries(SOURCE_NAMES.map(n=>[n,{path:`specs/feature/${n}.md`,sha256:designAdvisorBytesSha256(sourceBytes[n])}]));const built=createInitialAdvisorContext({repoFingerprint:H,featureId:'feature',authoringDispatchId:'author',initialCandidate:I,sources,sourceBytes,reason:'architecture-tradeoff',routePolicySha256:H,createdAt:DATE});assert.equal(built.ok,true);return {initial:built.context,sourceBytes};}
function binding(){const {initial}=fixture(),courseId='dac_course',consultation={courseId,initialContextSha256:designAdvisorValueSha256(initial),dispatch:{dispatchId:'advisor',queueRevision:0,candidateCommit:I.commit,candidateTree:I.tree},questionSha256:initial.questionSha256,evidenceSha256:initial.evidenceSha256,receiptSha256:H,answerSha256:H,reportCanonicalSha256:H,proposalSetSha256:designAdvisorValueSha256([{proposalId:'p1',text:'Require preserved input.'}])};const disposition={schema:'pipeline.design-advisor-disposition.v1',courseId,consultationSha256:designAdvisorValueSha256(consultation),proposalSetSha256:consultation.proposalSetSha256,items:[{proposalId:'p1',decision:'adopt',rationale:'Preserves original requirement.',revisionCommit:F.commit}],ownerDispatchId:'owner',createdAt:DATE};const sources=structuredClone(initial.sources);sources.design.sha256='2'.repeat(64);const revisions=[{schema:'pipeline.design-advisor-revision.v1',courseId,seq:1,priorRevisionSha256:null,candidate:F,sources,parentCommit:I.commit,proposalIds:['p1'],reason:'advisor-disposition'}];return {initial,courseId,consultation,disposition,revisions,final:{candidate:F,sources}};}
test('initial context builds one canonical question and the existing evidence digest from real Unicode/CRLF bytes',()=>{const {initial,sourceBytes}=fixture();assert.equal(hashInitialAdvisorQuestion({reason:initial.reason,sources:initial.sources}),initial.questionSha256);const bundle={schema:'pipeline.advisory-evidence-bundle.v1',references:SOURCE_NAMES.map(n=>({path:initial.sources[n].path,sha256:initial.sources[n].sha256,bytes:sourceBytes[n].length,content:sourceBytes[n].toString('utf8')})).sort((a,b)=>a.path.localeCompare(b.path))};assert.equal(advisoryEvidenceBundleSha256(bundle),initial.evidenceSha256);assert.equal(validateInitialAdvisorContext(initial,{sourceBytes}).ok,true);assert.match(buildInitialAdvisorQuestion({reason:initial.reason,sources:initial.sources}),/initial design/);});
test('legacy raw-design question, wrong evidence, invalid UTF8, private/aliased paths and unknown fields are refused',()=>{const {initial,sourceBytes}=fixture();for(const mutation of [i=>i.questionSha256=designAdvisorBytesSha256(sourceBytes.design),i=>i.evidenceSha256='f'.repeat(64),i=>i.sources.design.path='specs/../private.md',i=>i.sources.design.path='.git/private.json',i=>i.extra=true]){const i=structuredClone(initial);mutation(i);assert.equal(validateInitialAdvisorContext(i,{sourceBytes}).ok,false);}const b={...sourceBytes,design:Buffer.from([0xc3,0x28])};const refs=structuredClone(initial.sources);refs.design.sha256=designAdvisorBytesSha256(b.design);assert.equal(createInitialAdvisorContext({...initial,sources:refs,sourceBytes:b}).ok,false);});
test('genuine initial receipt binding remains initial after advice-driven final revision; pure check does not claim physical authority',()=>{const b=binding();const result=validateInitialToFinalBinding(b);assert.equal(result.ok,true);assert.equal(result.physicalProvenanceVerified,false);assert.equal(result.implementationAuthority,false);assert.notEqual(b.consultation.dispatch.candidateCommit,b.final.candidate.commit);assert.notEqual(b.initial.sources.design.sha256,b.final.sources.design.sha256);});
test('new packaging commit extends explicit chain without rewriting the initial consultation',()=>{const b=binding(),previous=b.revisions[0],candidate={commit:'e'.repeat(40),tree:F.tree};b.revisions.push({schema:'pipeline.design-advisor-revision.v1',courseId:b.courseId,seq:2,priorRevisionSha256:designAdvisorValueSha256(previous),candidate,sources:previous.sources,parentCommit:F.commit,proposalIds:[],reason:'packaging-only'});b.final={candidate,sources:previous.sources};assert.equal(validateInitialToFinalBinding(b).ok,true);});
test('relabeled receipt, detached chain, invented proposal adoption, changed input, and wrong final endpoint are refused',()=>{for(const mutation of [b=>b.consultation.dispatch.candidateCommit=F.commit,b=>b.revisions[0].parentCommit=F.commit,b=>b.revisions[0].proposalIds=['invented'],b=>b.revisions[0].sources.input.sha256='9'.repeat(64),b=>b.final.candidate={commit:'e'.repeat(40),tree:F.tree},b=>b.disposition.items.push({...b.disposition.items[0]}),b=>b.revisions[0].priorRevisionSha256=H]){const b=binding();mutation(b);assert.equal(validateInitialToFinalBinding(b).ok,false);}});
test('unchanged sources allow empty revision chain with zero adopted proposals',()=>{const b=binding();b.disposition.items=[];b.revisions=[];b.final={candidate:b.initial.initialCandidate,sources:b.initial.sources};assert.equal(validateInitialToFinalBinding(b).ok,true);});

// Each original sibling callback is registered individually; no envelope case.
if (completionCases.length !== 6) throw new Error("Required completion declared case count drift");
const completionFd = process.env.PIPELINE_VERIFY_CASE_COMPLETION_FD === undefined
  ? openCompletionDescriptor(devNull, "w")
  : Number(process.env.PIPELINE_VERIFY_CASE_COMPLETION_FD);
registerTestCaseCompletion({ cases: completionCases, fd: completionFd,
  maxBytes: Number(process.env.PIPELINE_VERIFY_CASE_COMPLETION_MAX_BYTES ?? "65536") });
