// SPDX-License-Identifier: SUL-1.0
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import {join} from 'node:path';
import {tmpdir, devNull} from 'node:os';
import {spawnSync} from 'node:child_process';
import {planEnrollmentGitCreation,applyEnrollmentGitCreation} from './project-onboarding-v3.mjs';
import {resolveOnboardingIntakeScope} from './codex-onboarding-runtime.mjs';
import {recordConsentGiven,observeEnrollmentRetirementConsent,retireEnrollmentConsent} from './onboarding-consent-marker.mjs';
import {registerTestCaseCompletion} from './test-case-completion.mjs';
const cases=[];const test=(id,name,run)=>cases.push({id,name,run});
function fixture(run){const root=fs.mkdtempSync(join(tmpdir(),'enrollment-owner-offline-'));try{return run(root);}finally{fs.rmSync(root,{recursive:true,force:true});}}
function adapter(root,{active=false,failPrepare=false}={}){let state=active?'active':'inactive',initializations=0,prepares=0;const dependencies={...fs,enrollmentObserve:()=>({root,state,repositoryKind:'non-git',provenance:{kind:'fixture'}}),enrollmentDecline:()=>{state='declined';},enrollmentPrepare:()=>{prepares++;if(failPrepare&&prepares===1)throw Error('OFFLINE-WRITER-UNAVAILABLE');},spawnSync:(exe,args,options)=>{if(args[0]==='init')initializations++;return spawnSync(exe,args,options);}};return {dependencies,get initializations(){return initializations;},get prepares(){return prepares;}};}
const plan=(root,a)=>planEnrollmentGitCreation({rootDir:root,runner:'codex',deps:a.dependencies});
const apply=p=>applyEnrollmentGitCreation({plan:p.plan,planSha256:p.plan.planSha256,requestCreateGit:true,activate:true});
function retained(root){fs.mkdirSync(join(root,'project'));fs.writeFileSync(join(root,'project','pipeline-state.json'),'{"fixture":"retained historical state"}\n');fs.mkdirSync(join(root,'.agent-pipeline'));fs.writeFileSync(join(root,'.agent-pipeline','onboarding-consent.json'),'{"schema":"pipeline.onboarding-consent-marker.v1","status":"consent-given-onboarding-incomplete","consentGivenAt":"2026-09-29T00:00:00.000Z"}\n');}
test('EGR01','explicit Git creation preserves retained State and consent bytes; privileged handoff is a fixture callback',()=>fixture(root=>{retained(root);const state=fs.readFileSync(join(root,'project','pipeline-state.json')),consent=fs.readFileSync(join(root,'.agent-pipeline','onboarding-consent.json')),a=adapter(root),p=plan(root,a);assert.equal(p.status,'planned');assert.equal(apply(p).status,'created');assert.deepEqual(fs.readFileSync(join(root,'project','pipeline-state.json')),state);assert.deepEqual(fs.readFileSync(join(root,'.agent-pipeline','onboarding-consent.json')),consent);assert.equal(a.initializations,1);assert.equal(a.prepares,1);assert.equal(JSON.parse(fs.readFileSync(join(root,'.agent-pipeline','enrollment-git-creation-barrier.json'))).phase,'retired');}));
test('EGR02','already active legacy is retained without creating Git or a removal marker',()=>fixture(root=>{retained(root);const a=adapter(root,{active:true}),before=fs.readdirSync(root);assert.equal(plan(root,a).status,'retained');assert.deepEqual(fs.readdirSync(root),before);assert.equal(fs.existsSync(join(root,'.git')),false);assert.equal(fs.existsSync(join(root,'.agent-pipeline','enrollment-git-creation.json')),false);}));
test('EGR03','explicit Git request is required even with a valid digest',()=>fixture(root=>{const a=adapter(root),p=plan(root,a);assert.equal(applyEnrollmentGitCreation({plan:p.plan,planSha256:p.plan.planSha256,activate:true}).code,'ER-GIT-EXPLICIT-REQUEST');assert.deepEqual(fs.readdirSync(root),[]);}));
test('EGR04','retained history drift refuses before a barrier or Git write',()=>fixture(root=>{retained(root);const a=adapter(root),p=plan(root,a);fs.writeFileSync(join(root,'project','pipeline-state.json'),'different bytes');assert.equal(apply(p).code,'ER-GIT-CAS');assert.equal(fs.existsSync(join(root,'.git')),false);assert.equal(fs.existsSync(join(root,'.agent-pipeline','enrollment-git-creation.json')),false);}));
test('EGR05','foreign Git control alias is left untouched',()=>fixture(root=>{const foreign=fs.mkdtempSync(join(tmpdir(),'foreign-control-'));try{fs.symlinkSync(foreign,join(root,'.git'));const a=adapter(root);assert.equal(plan(root,a).code,'ER-GIT-CONTROL-PRESENT');assert.deepEqual(fs.readdirSync(foreign),[]);assert.equal(fs.readlinkSync(join(root,'.git')),foreign);}finally{fs.rmSync(foreign,{recursive:true,force:true});}}));
test('EGR06','host private history refuses without guessing a capability',()=>fixture(root=>{fs.mkdirSync(join(root,'.claude','.runtime','agent-pipeline','onboarding'),{recursive:true});fs.writeFileSync(join(root,'.claude','.runtime','agent-pipeline','onboarding','retained'),'exact bytes');assert.equal(plan(root,adapter(root)).code,'ER-GIT-HOST-PRIVATE-HISTORY');assert.equal(fs.readFileSync(join(root,'.claude','.runtime','agent-pipeline','onboarding','retained'),'utf8'),'exact bytes');assert.equal(fs.existsSync(join(root,'.git')),false);}));
test('EGR07','writer handoff failure keeps a durable removal barrier and resumes the same request without reinitializing Git',()=>fixture(root=>{retained(root);const a=adapter(root,{failPrepare:true}),p=plan(root,a),first=apply(p);assert.equal(first.status,'refused');assert.match(first.code,/OFFLINE-WRITER-UNAVAILABLE/);assert.equal(JSON.parse(fs.readFileSync(join(root,'.agent-pipeline','enrollment-git-creation-barrier.json'))).phase,'created');const resumed=plan(root,a);assert.equal(resumed.plan.planSha256,p.plan.planSha256);assert.equal(apply(resumed).status,'created');assert.equal(a.initializations,1);assert.equal(a.prepares,2);}));
test('EGR08','no-history local root takes explicit canonical Git creation without a host private directory',()=>fixture(root=>{const a=adapter(root),p=plan(root,a);assert.equal(p.plan.retained.every(row=>row.status==='absent'),true);assert.equal(apply(p).status,'created');assert.equal(fs.existsSync(join(root,'.claude','.runtime')),false);}));
test('EGR09','real consent CAS preserves fresh marker and retires only exact archived bytes',()=>fixture(root=>{recordConsentGiven({rootDir:root,now:new Date('2026-09-29T00:00:00.000Z')});const old=observeEnrollmentRetirementConsent({rootDir:root});fs.unlinkSync(old.path);recordConsentGiven({rootDir:root,now:new Date('2026-09-29T00:00:01.000Z')});const fresh=observeEnrollmentRetirementConsent({rootDir:root});assert.throws(()=>retireEnrollmentConsent({rootDir:root,expectedSha256:old.sha256}),/FRESH-DRIFT/);assert.deepEqual(fs.readFileSync(fresh.path),fresh.bytes);assert.equal(retireEnrollmentConsent({rootDir:root,expectedSha256:fresh.sha256}).sha256,null);assert.equal(retireEnrollmentConsent({rootDir:root,expectedSha256:fresh.sha256}).replayed,true);}));
test('EGR10','real selected worktrees isolate current intake paths and preserve foreign exact bytes',()=>fixture(root=>{const main=join(root,'main'),other=join(root,'other');fs.mkdirSync(main);for(const args of [['init','--initial-branch=main'],['-c','user.name=offline-fixture','-c','user.email=offline@example.invalid','-c','commit.gpgsign=false','commit','--allow-empty','-m','offline fixture'],['worktree','add',other]]){const result=spawnSync('git',args,{cwd:main,encoding:'utf8'});assert.equal(result.status,0,result.stderr);}const a=resolveOnboardingIntakeScope(main,'local',{create:true}),b=resolveOnboardingIntakeScope(other,'local',{create:true});assert.notEqual(a.directory,b.directory);assert.equal(a.legacyDirectory,b.legacyDirectory);fs.writeFileSync(join(a.directory,'consumed-intake-fixture'),'exact foreign consumed consent bytes');const before=fs.readFileSync(join(a.directory,'consumed-intake-fixture'));resolveOnboardingIntakeScope(other,'local',{create:true});assert.deepEqual(fs.readFileSync(join(a.directory,'consumed-intake-fixture')),before);}));
const fd=process.env.PIPELINE_VERIFY_CASE_COMPLETION_FD===undefined?fs.openSync(devNull,'w'):Number(process.env.PIPELINE_VERIFY_CASE_COMPLETION_FD);
registerTestCaseCompletion({cases,fd,maxBytes:Number(process.env.PIPELINE_VERIFY_CASE_COMPLETION_MAX_BYTES??'131072')});
