#!/usr/bin/env node
// SPDX-License-Identifier: SUL-1.0
import assert from "node:assert/strict";
import { createExecutionSubject, createExecutionPlaneRequest, createExecutionState, executionSubjectDigest, normalizeSyntheticExecutionOutcome, reduceExecutionState, validateExecutionPlaneRequest } from "./execution-plane-contract.mjs";

const A = "a".repeat(64), B = "b".repeat(64), O = "1".repeat(40);
const subject = createExecutionSubject({ repository:{identitySha256:A}, baseCommit:O, baseTree:O, candidateCommit:O, candidateTree:O, packageId:"pkg", dispatchId:"dispatch", attempt:"attempt", queueRevision:0, authorityDigests:[{kind:"spec",sha256:A}], writePaths:["lib/pkg.mjs"], resources:["cpu"] });
const request = createExecutionPlaneRequest({ requestId:"request", subject, adapter:{kind:"synthetic",version:"v1",implementationSha256:A}, locality:"in-process", workspace:{identitySha256:A,separation:"observed",assuranceEvidenceSha256:B}, network:{mode:"none",egressClasses:[]}, mounts:[], writePaths:["lib/pkg.mjs"], resources:[{unit:"cpu",limit:1}], sidecars:[], credentialLease:null, heartbeat:{intervalMs:10,orphanAfterMs:20}, timeout:{absoluteMs:100,maxPauseMs:0}, cancellation:{supported:true,deadlineMs:10}, resultDelivery:{mode:"inline-digest",maxBytes:10,destinationClass:"result"}, frozenBinding:{controlExecutionExchangeSha256:A,invocationRequestSha256:B} });
let passed = 0; const check = (name, fn) => { fn(); passed += 1; console.log(`PASS EPC${String(passed).padStart(2,"0")} ${name}`); };
const outcome = (kind, result = null, candidateCommit = O) => ({ dispatchId:"dispatch", attempt:"attempt", candidateCommit, kind, evidenceSha256:B, result });
check("builds a closed, digested subject and request", () => { assert.equal(executionSubjectDigest(subject).length, 64); assert.equal(validateExecutionPlaneRequest(request).ok, true); assert.equal(Object.isFrozen(request), true); });
check("rejects path/candidate/frozen-binding drift before an execution request exists", () => { assert.throws(() => createExecutionPlaneRequest({ ...request, writePaths:["elsewhere"] })); assert.throws(() => createExecutionPlaneRequest({ ...request, locality:"external-live" })); });
check("normalizes success as unverified and reserves verified for matching verifier evidence", () => { let state = createExecutionState(subject); state = reduceExecutionState(state, outcome("admitted")).state; state = reduceExecutionState(state, outcome("running")).state; const success = reduceExecutionState(state, outcome("success", {resultSha256:A,bytes:1,status:"delivered"})); assert.equal(success.state.state, "succeeded-unverified"); assert.equal(normalizeSyntheticExecutionOutcome(success.state, outcome("verifierPassed", {resultSha256:B,bytes:1,status:"delivered"})).code, "AUTHORITY:verifier"); const verified = reduceExecutionState(success.state, outcome("verifierPassed", {resultSha256:A,bytes:1,status:"delivered"})); assert.equal(verified.state.state, "verified"); });
check("covers duplicate, out-of-order, stale candidate, failure, timeout, cancellation, lost heartbeat and completed-undelivered without false success", () => { const state = createExecutionState(subject); assert.equal(normalizeSyntheticExecutionOutcome(state, outcome("duplicate")).code, "REPLAY:duplicate"); assert.equal(normalizeSyntheticExecutionOutcome(state, outcome("outOfOrder")).code, "STALE:out-of-order"); assert.equal(normalizeSyntheticExecutionOutcome(state, outcome("running", null, "2".repeat(40))).code, "STALE:outcome"); let running = reduceExecutionState(reduceExecutionState(state, outcome("admitted")).state, outcome("running")).state; assert.equal(reduceExecutionState(running, outcome("failure")).state.state, "failed"); assert.equal(reduceExecutionState(running, outcome("timeout")).state.state, "timed-out"); const requested=reduceExecutionState(running,outcome("cancel")).state; assert.equal(requested.state,"cancel-requested"); assert.equal(reduceExecutionState(requested,outcome("cancel")).state.state,"cancelled"); assert.equal(reduceExecutionState(running, outcome("lostHeartbeat")).state.state, "lost"); assert.equal(reduceExecutionState(running, outcome("completedUndelivered")).state.state, "completed-undelivered"); });
console.log(`${passed}/4 checks passed.`);
