// SPDX-License-Identifier: SUL-1.0
import assert from "node:assert/strict";
import { createHash, generateKeyPairSync, sign } from "node:crypto";
import test from "node:test";
import { createRawObservation, createVexRecord, evaluateReleaseGate, exportFindingMetrics, normalizeFinding, projectFinding, reevaluateForDrift, transitionFinding, validateWaiver, verifyClosure, RECORD_TYPES } from "./finding-lifecycle.mjs";
import { createSecurityAuthorityIntent, SECURITY_AUTHORITY_SCHEMA, securityAuthorityScopeSha256 } from "./security-authority-proof.mjs";

const a = "a".repeat(64); const b = "b".repeat(64);
const finding = { id: "fnd-1", state: "confirmed", candidateSha256: a };
const candidate = { commit: "1".repeat(40), tree: "2".repeat(40) };

function signedAuthority(action, candidateSha256, policySha256, scope) {
  const { privateKey, publicKey } = generateKeyPairSync("ed25519");
  const publicKeyPem = publicKey.export({ type: "spki", format: "pem" });
  const authorityContext = { candidate, planSha256: a, specSha256: b, policyRevision: "security-policy-v1", trustPolicy: { keyReference: "test-po", publicKeySha256: createHash("sha256").update(publicKeyPem).digest("hex") } };
  const intent = createSecurityAuthorityIntent({ featureId: "cyb-8", action, candidate, candidateSha256, policySha256, scopeSha256: securityAuthorityScopeSha256(scope), planSha256: authorityContext.planSha256, specSha256: authorityContext.specSha256, policyRevision: authorityContext.policyRevision });
  const proof = { schema: "pipeline.po-approval-proof.v1", intentSha256: intent.sha256, keyReference: "test-po", publicKey: publicKeyPem, signatureBase64: sign(null, Buffer.from(intent.sha256, "utf8"), privateKey).toString("base64") };
  return { authorityContext, authority: { schema: SECURITY_AUTHORITY_SCHEMA, kind: "human", intent, proof } };
}

test("AC1: seven lifecycle artifact classes remain distinct", () => assert.deepEqual(RECORD_TYPES, ["raw-observation", "normalized-finding", "triage", "vex", "waiver", "remediation", "approval"]));
test("AC2: scanner migrations deduplicate to a stable component/candidate identity", () => assert.equal(normalizeFinding({ component: "pkg:npm/a@1", vulnerability: "CVE-1", location: "a.js:1", candidateSha256: a }).findingId, normalizeFinding({ component: "pkg:npm/a@1", vulnerability: "CVE-1", location: "a.js:1", candidateSha256: a }).findingId));
test("AC3: untyped or unauthorized transitions fail closed", () => { assert.equal(transitionFinding({ finding, to: "affected" }).accepted, false); assert.equal(transitionFinding({ finding, to: "false-positive", authority: "agent", reason: "no", at: "2026-08-02", candidateSha256: a, policySha256: b }).accepted, false); });
test("AC4: absence is not a VEX disposition and VEX binds to SBOM", () => { const input = { findingId: "f", componentPurl: "pkg:npm/a@1", sbomSha256: a, productVersion: "1", candidateSha256: b, policySha256: a, disposition: "not-affected" }; const signed = signedAuthority("vex-not-affected", input.candidateSha256, input.policySha256, { findingId: input.findingId, componentPurl: input.componentPurl, sbomSha256: input.sbomSha256, productVersion: input.productVersion, disposition: input.disposition }); assert.equal(createVexRecord({ ...input, ...signed }).accepted, true); assert.equal(createVexRecord({ ...input, authority: "human", authorityContext: signed.authorityContext }).accepted, false); assert.equal(createVexRecord({ ...input, disposition: "absent", ...signed }).accepted, false); });
test("AC5: waivers need controls, expiry, and exact scope/policy", () => { const waiver = { reason: "bounded", compensatingControls: ["monitor"], expiresAt: "2026-09-01", candidateSha256: a, policySha256: b }; const signed = signedAuthority("waive-finding", a, b, { ...waiver }); waiver.authority = signed.authority; assert.equal(validateWaiver({ waiver, authorityContext: signed.authorityContext, at: "2026-08-02", candidateSha256: a, policySha256: b }).status, "current"); assert.equal(validateWaiver({ waiver, authorityContext: signed.authorityContext, at: "2026-08-02", candidateSha256: b, policySha256: b }).status, "stale"); });
test("AC6: only detached human or policy proof can approve a terminal disposition", () => { const input = { finding: { ...finding, state: "affected" }, to: "accepted-risk", reason: "risk", at: "2026-08-02", candidateSha256: a, policySha256: b }; const signed = signedAuthority(input.to, a, b, { findingId: input.finding.id, to: input.to, reason: input.reason, at: input.at }); assert.equal(transitionFinding({ ...input, authority: "agent" }).accepted, false); assert.equal(transitionFinding({ ...input, authority: "human", authorityContext: signed.authorityContext }).accepted, false); assert.equal(transitionFinding({ ...input, ...signed }).accepted, true); });
test("AC7: closure requires patch, replay, regression, and independent confirmation", () => { assert.equal(verifyClosure({ findingId: "f", candidateSha256: a, patchSha256: a, regressionSha256: b, confirmedBy: "reviewer", authorId: "author" }).accepted, false); assert.equal(verifyClosure({ findingId: "f", candidateSha256: a, patchSha256: a, replaySha256: b, regressionSha256: a, confirmedBy: "reviewer", authorId: "author" }).accepted, true); });
test("AC8: stale external dashboard state cannot unblock canonical release", () => assert.equal(evaluateReleaseGate({ findings: [{ id: "f", state: "affected", candidateSha256: a, dashboard: "resolved" }], candidateSha256: a }).allowed, false));
test("AC9: all drift triggers reopen or stale determinstically", () => { for (const trigger of ["candidate", "component", "scanner-rule-data", "threat-control", "waiver-expiry", "exploitability", "recurrence"]) assert.ok(["reopened", "stale"].includes(reevaluateForDrift({ finding, trigger }).state)); });
test("AC10: projection writes cannot alter canonical record", () => { const canonical = Object.freeze({ id: "f", state: "affected" }); const projection = projectFinding(canonical, { state: "resolved" }); assert.equal(canonical.state, "affected"); assert.deepEqual(projection.rejectedExternalFields, ["state"]); });
test("AC11: duplicate, false-positive, not-affected, accepted-risk, expiry, recurrence, reopened and migration fixtures are represented", () => { assert.equal(createRawObservation({ scanner: "v2", payloadSha256: a, observedAt: "2026-08-02" }).type, "raw-observation"); assert.equal(reevaluateForDrift({ finding, trigger: "recurrence" }).state, "reopened"); });
test("AC12: metrics have no raw finding content", () => { const metrics = exportFindingMetrics({ triageHours: [2], remediationHours: [8], recurrenceCount: 1, waiverAgesDays: [3], escapeCount: 0, completeEvidence: 2, totalEvidence: 2 }); assert.equal(JSON.stringify(metrics).includes("CVE"), false); assert.equal(metrics.evidenceCompleteness, 1); });
