// SPDX-License-Identifier: SUL-1.0
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { canonicalForgeJson } from "./forge-capability.mjs";
import { createGitLabCiBrokerRequest, observeGitLabCiBroker, reconcileGitLabCiBroker, submitGitLabCiBroker, validateGitLabCiBroker } from "./gitlab-ci-execution-broker.mjs";
const A = "a".repeat(64), C = "c".repeat(40), T = "d".repeat(40);
const request = () => createGitLabCiBrokerRequest({ requestId: "nova-b2-pilot", candidate: { commit: C, tree: T }, target: { baseUrlClass: "gitlab-com", projectCoordinatesSha256: A, operatorAuthoritySha256: A }, idempotencyKey: A });
const observation = (record, providerState, providerSequence, observedAt) => { const targetSha256 = createHash("sha256").update(`pipeline.gitlab-ci-execution-broker.v1\0${canonicalForgeJson(record.target)}`, "utf8").digest("hex"); const value = { sequence: record.observations.length + 1, providerState, providerSequence, jobIdSha256: record.job.jobIdSha256, candidateCommit: record.candidate.commit, targetSha256, observedAt, observationSha256: "" }; value.observationSha256 = createHash("sha256").update(`pipeline.gitlab-ci-execution-observation.v1\0${canonicalForgeJson({ ...value, observationSha256: undefined })}`, "utf8").digest("hex"); return value; };
const check = (n, fn) => { try { fn(); process.stdout.write(`PASS ${n}\n`); } catch (e) { process.stderr.write(`FAIL ${n}: ${e.stack}\n`); process.exitCode = 1; } };
check("B2 request never represents a token and job submission permits CI_JOB_TOKEN only", () => { assert.throws(() => createGitLabCiBrokerRequest({ ...request(), token: "x" }), /SHAPE/u); const r = submitGitLabCiBroker(request(), { jobIdSha256: A, tokenMode: "ci-job-token-only", submittedAt: 1 }).broker; assert.equal(r.state, "submitted"); assert.equal(submitGitLabCiBroker(request(), { jobIdSha256: A, tokenMode: "operator-token", submittedAt: 1 }).ok, false); });
check("provider success remains unverified until a second exact metadata observation", () => { let r = submitGitLabCiBroker(request(), { jobIdSha256: A, tokenMode: "ci-job-token-only", submittedAt: 1 }).broker; r = observeGitLabCiBroker(r, { providerState: "success", providerSequence: 1, observedAt: 2 }).broker; assert.equal(r.state, "succeeded-unverified"); r = reconcileGitLabCiBroker(r, observation(r, "success", 2, 3)).broker; assert.equal(r.state, "reconciled"); assert.deepEqual(validateGitLabCiBroker(r), { ok: true, code: null }); });
check("reconciliation rejects manufactured or credential-shaped observations", () => { let r = submitGitLabCiBroker(request(), { jobIdSha256: A, tokenMode: "ci-job-token-only", submittedAt: 1 }).broker; r = observeGitLabCiBroker(r, { providerState: "success", providerSequence: 1, observedAt: 2 }).broker; assert.equal(reconcileGitLabCiBroker(r, { observedAt: 3 }).ok, false); assert.equal(reconcileGitLabCiBroker(r, { ...observation(r, "success", 2, 3), token: "x" }).ok, false); });
check("duplicate and out-of-order provider metadata cannot change the broker", () => { let r = submitGitLabCiBroker(request(), { jobIdSha256: A, tokenMode: "ci-job-token-only", submittedAt: 1 }).broker; r = observeGitLabCiBroker(r, { providerState: "running", providerSequence: 2, observedAt: 3 }).broker; const duplicate = observeGitLabCiBroker(r, { providerState: "running", providerSequence: 2, observedAt: 3 }); assert.equal(duplicate.ok, true); assert.equal(duplicate.code, "DUPLICATE:broker-observation"); assert.equal(duplicate.broker, r); assert.equal(observeGitLabCiBroker(r, { providerState: "queued", providerSequence: 1, observedAt: 4 }).ok, false); r = observeGitLabCiBroker(r, { providerState: "success", providerSequence: 3, observedAt: 5 }).broker; assert.equal(observeGitLabCiBroker(r, { providerState: "running", providerSequence: 4, observedAt: 6 }).ok, false); });
check("cancellation is a bound provider observation, not an optimistic terminal claim", () => { let r = submitGitLabCiBroker(request(), { jobIdSha256: A, tokenMode: "ci-job-token-only", submittedAt: 1 }).broker; r = observeGitLabCiBroker(r, { providerState: "cancel-requested", providerSequence: 1, observedAt: 2 }).broker; assert.equal(r.state, "cancel-requested"); r = observeGitLabCiBroker(r, { providerState: "cancelled", providerSequence: 2, observedAt: 3 }).broker; assert.equal(r.state, "cancelled"); });
check("hostile timing, job substitution and raw credential fields cannot reconcile", () => { let r = submitGitLabCiBroker(request(), { jobIdSha256: A, tokenMode: "ci-job-token-only", submittedAt: 2 }).broker; assert.equal(observeGitLabCiBroker(r, { providerState: "success", providerSequence: 1, observedAt: 1 }).ok, false); r = observeGitLabCiBroker(r, { providerState: "running", providerSequence: 1, observedAt: 3 }).broker; const bad = structuredClone(r); bad.observations[0].jobIdSha256 = "b".repeat(64); bad.recordSha256 = "0".repeat(64); assert.equal(validateGitLabCiBroker(bad).ok, false); });
check("published observation schema requires strings for every bound identifier", () => { const schema = JSON.parse(readFileSync(new URL("../scripts/gitlab-ci-execution-broker-observation.schema.json", import.meta.url), "utf8")); for (const key of ["jobIdSha256", "candidateCommit", "targetSha256", "observationSha256"]) assert.equal(schema.properties[key].type, "string"); });
