// SPDX-License-Identifier: SUL-1.0
import assert from "node:assert/strict";
import { createGitLabCiBrokerRequest, observeGitLabCiBroker, reconcileGitLabCiBroker, submitGitLabCiBroker, validateGitLabCiBroker } from "./gitlab-ci-execution-broker.mjs";
const A = "a".repeat(64), C = "c".repeat(40), T = "d".repeat(40);
const request = () => createGitLabCiBrokerRequest({ requestId: "nova-b2-pilot", candidate: { commit: C, tree: T }, target: { baseUrlClass: "gitlab-com", projectCoordinatesSha256: A, operatorAuthoritySha256: A }, idempotencyKey: A });
const check = (n, fn) => { try { fn(); process.stdout.write(`PASS ${n}\n`); } catch (e) { process.stderr.write(`FAIL ${n}: ${e.stack}\n`); process.exitCode = 1; } };
check("B2 request never represents a token and job submission permits CI_JOB_TOKEN only", () => { assert.throws(() => createGitLabCiBrokerRequest({ ...request(), token: "x" }), /SHAPE/u); const r = submitGitLabCiBroker(request(), { jobIdSha256: A, tokenMode: "ci-job-token-only", submittedAt: 1 }).broker; assert.equal(r.state, "submitted"); assert.equal(submitGitLabCiBroker(request(), { jobIdSha256: A, tokenMode: "operator-token", submittedAt: 1 }).ok, false); });
check("provider success remains unverified until a second exact metadata observation", () => { let r = submitGitLabCiBroker(request(), { jobIdSha256: A, tokenMode: "ci-job-token-only", submittedAt: 1 }).broker; r = observeGitLabCiBroker(r, { providerState: "success", observedAt: 2 }).broker; assert.equal(r.state, "succeeded-unverified"); r = reconcileGitLabCiBroker(r, { observedAt: 3 }).broker; assert.equal(r.state, "reconciled"); assert.deepEqual(validateGitLabCiBroker(r), { ok: true, code: null }); });
check("cancellation is a bound provider observation, not an optimistic terminal claim", () => { let r = submitGitLabCiBroker(request(), { jobIdSha256: A, tokenMode: "ci-job-token-only", submittedAt: 1 }).broker; r = observeGitLabCiBroker(r, { providerState: "cancel-requested", observedAt: 2 }).broker; assert.equal(r.state, "cancel-requested"); r = observeGitLabCiBroker(r, { providerState: "cancelled", observedAt: 3 }).broker; assert.equal(r.state, "cancelled"); });
check("hostile timing, job substitution and raw credential fields cannot reconcile", () => { let r = submitGitLabCiBroker(request(), { jobIdSha256: A, tokenMode: "ci-job-token-only", submittedAt: 2 }).broker; assert.equal(observeGitLabCiBroker(r, { providerState: "success", observedAt: 1 }).ok, false); r = observeGitLabCiBroker(r, { providerState: "running", observedAt: 3 }).broker; const bad = structuredClone(r); bad.observations[0].jobIdSha256 = "b".repeat(64); bad.recordSha256 = "0".repeat(64); assert.equal(validateGitLabCiBroker(bad).ok, false); });
