// Source target: plugins/pipeline-core/lib/governance-scope.test.mjs
import { registerTestCaseCompletion } from "./test-case-completion.mjs";
import { openSync as openCompletionDescriptor } from "node:fs";

const completionCases = [];
function test(name, run) {
  if (arguments.length !== 2 || typeof run !== "function") throw new TypeError("Required completion expects the preserved two-argument test registration");
  completionCases.push({ id: "RC14C" + String(completionCases.length + 1).padStart(3, "0"), name, run });
}
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {chmodSync,existsSync,linkSync,mkdtempSync,mkdirSync,readFileSync,readdirSync,renameSync,rmSync,symlinkSync,truncateSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,dirname} from 'node:path';
import {createGovernanceScopeController,readGovernanceEnrollmentRetirement,governanceEnrollmentRecoveryAction} from './governance-scope.mjs';
import {hasCodexGitControlMount} from './codex-host-layout.mjs';
import {loadRunnerProfilesV3Registry} from './runner-profiles-v3.mjs';
import {codexCustomAgentSeed,planRuntimeProjectionV3} from './runtime-projection-v3.mjs';
import {freshCalibrationBytes,freshManifestBytes} from './project-onboarding-v3.mjs';
import {validateAgainstSchema} from './schema-lite.mjs';
import scopeSchema from '../schemas/pipeline.governance-scope.v1.json' with {type:'json'};
function fixture(t,{git=false}={}){const base=mkdtempSync(join(tmpdir(),'governance-scope-')),root=join(base,'repo'),host=join(base,'host-store');mkdirSync(root);if(git){runGit(root,['init','--initial-branch=main']);runGit(root,['config','user.name','Fixture']);runGit(root,['config','user.email','fixture@example.invalid']);runGit(root,['commit','--allow-empty','-m','fixture']);}t.after(()=>rmSync(base,{recursive:true,force:true}));return{base,root,host,controller:createGovernanceScopeController({hostStateRoot:host})};}
function runGit(root,args){const r=spawnSync('git',args,{cwd:root,encoding:'utf8',timeout:5000,shell:false});assert.equal(r.status,0,JSON.stringify({args,stderr:r.stderr,error:r.error?.code}));return r.stdout.trim();}
function files(root,prefix=''){const result=[];for(const entry of readdirSync(root,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){const path=join(root,entry.name),rel=prefix+entry.name;if(entry.isDirectory())result.push(...files(path,rel+'/'));else result.push([rel,readFileSync(path).toString('hex')]);}return result;}
function decide(controller,root,decision){const plan=controller.planDecision({rootDir:root,decision,by:'Fixture human answer'});return controller.applyDecision(plan,{activate:true,planSha256:plan.planSha256});}
function put(root,path,bytes){const dest=join(root,path);mkdirSync(dirname(dest),{recursive:true});writeFileSync(dest,bytes);}
function fixtureYaml(value,indent=''){
  if(Array.isArray(value))return value.map(item=>item&&typeof item==='object'?indent+'-\n'+fixtureYaml(item,indent+'  '):indent+'- '+JSON.stringify(item)+'\n').join('');
  return Object.entries(value).map(([key,item])=>item&&typeof item==='object'?indent+key+':\n'+fixtureYaml(item,indent+'  '):indent+key+': '+JSON.stringify(item)+'\n').join('');
}
function seedV3(root){
  const registry=loadRunnerProfilesV3Registry(),intent={schema:'pipeline.user.v3',language:{human_facing:'de',agent_facing:'en'},agent_runtime:'other',runners:{enabled:['claude','codex'],default:'codex'},routing:{profiles:registry.profiles,duties:registry.duties},usage:{common_projection:'pipeline.runner-usage.v1',raw_persistence:'none'},autonomy:{push_policy:'gated',branch_model:'feature-branch',wip_limit:1},gates:{dev_plan:'blocking',push:'blocking',security:'warn',claude_md_max_lines:300},critic_export:registry.criticExportPolicy,session:{keep_awake:true}};
  const values={'.claude/pipeline.yaml':freshManifestBytes(),'.claude/settings.json':'{}\n','.claude/pipeline.json':'{}\n','.codex/config.toml':'','.codex/agents/implementor.toml':codexCustomAgentSeed('implementor'),'.codex/agents/critic.toml':codexCustomAgentSeed('critic'),'.codex/agents/consult-advisor.toml':''};
  const baselines=Object.fromEntries(Object.entries(values).map(([path,bytes])=>[path,{status:'present',bytes}]));
  const plan=planRuntimeProjectionV3(intent,{baselines});assert.equal(plan.status,'ready',JSON.stringify(plan.diagnostics));
  const manifest=plan.targets.find(row=>row.path==='.claude/pipeline.yaml').after.bytes;put(root,'pipeline.user.yaml',fixtureYaml(intent));put(root,'.claude/pipeline.yaml',manifest);return manifest;
}

test('documents, entry pointers and malformed arbitrary source never enroll; observation writes nothing',t=>{const f=fixture(t);for(const path of ['AGENTS.md','CLAUDE.md','architecture/map/index.md','specs/example/spec.md'])put(f.root,path,'Run pipeline-start; retained content.\n');put(f.root,'pipeline.user.yaml','not: an-enrollment\n');const before=files(f.base);for(let i=0;i<2;i++){const obs=f.controller.observe({rootDir:f.root});assert.equal(obs.state,'inactive');assert.equal(obs.requiresEnforcement,false);assert.equal(obs.hintAllowed,true);}assert.deepEqual(files(f.base),before);assert.equal(existsSync(f.host),false);});

test('actual Git config stores a parseable root-bound decision and preserves unrelated bytes and mode',t=>{const f=fixture(t,{git:true}),config=join(f.root,'.git','config'),before=readFileSync(config,'utf8');assert.equal(existsSync(f.host),false);const inert=files(f.base);createGovernanceScopeController({hostStateRoot:f.host}).observe({rootDir:f.root});assert.deepEqual(files(f.base),inert);chmodSync(config,0o644);const active=decide(f.controller,f.root,'enroll');assert.equal(active.state,'active');const after=readFileSync(config,'utf8');assert.ok(after.startsWith(before));const json=runGit(f.root,['config','--local','--get',`agent-pipeline.activation-${active.scopeKey}.record`]);assert.equal(JSON.parse(json).state,'active');assert.equal(createGovernanceScopeController({hostStateRoot:f.host}).observe({rootDir:f.root}).state,'active');put(f.root,'.git/agent-pipeline/private-fixture.json','{}');decide(f.controller,f.root,'decline');rmSync(join(f.root,'.git','agent-pipeline'),{recursive:true});const snapshot=files(f.base),denied=createGovernanceScopeController({hostStateRoot:f.host}).observe({rootDir:f.root});assert.equal(denied.state,'declined');assert.equal(denied.hintAllowed,false);assert.equal(denied.requiresEnforcement,false);assert.deepEqual(files(f.base),snapshot);assert.ok(existsSync(join(f.host,active.scopeKey+'.git-proof.json')));assert.equal(readGovernanceEnrollmentRetirement({rootDir:f.root}),null);const again=decide(f.controller,f.root,'enroll');assert.equal(again.state,'active');assert.equal(readGovernanceEnrollmentRetirement({rootDir:f.root}),null);});

test('actual linked worktrees enroll independently; linked decline does not deactivate primary',t=>{const f=fixture(t,{git:true}),linked=join(f.base,'linked');runGit(f.root,['worktree','add','--detach',linked,'HEAD']);decide(f.controller,f.root,'enroll');decide(f.controller,linked,'enroll');decide(f.controller,linked,'decline');assert.equal(f.controller.observe({rootDir:f.root}).state,'active');assert.equal(f.controller.observe({rootDir:linked}).state,'declined');const child=join(f.root,'child');mkdirSync(child);assert.equal(f.controller.observe({rootDir:child}).root,f.root);assert.equal(f.controller.observe({rootDir:child}).state,'active');});

test('non-Git decline persists only in sealed fixture host store and restores explicit enrollment',t=>{const f=fixture(t);const before=files(f.root);assert.equal(decide(f.controller,f.root,'decline').state,'declined');assert.deepEqual(files(f.root),before);const again=createGovernanceScopeController({hostStateRoot:f.host});assert.equal(again.observe({rootDir:f.root}).state,'declined');assert.equal(decide(again,f.root,'enroll').state,'active');assert.equal(again.observe({rootDir:f.root}).requiresEnforcement,true);});

test('existing exact onboarding consent qualifies partial enrollment; corrupt marker alone cannot activate',t=>{const f=fixture(t);const empty=files(f.base);assert.equal(readGovernanceEnrollmentRetirement({rootDir:f.root}),null);assert.deepEqual(files(f.base),empty);put(f.root,'.agent-pipeline/onboarding-consent.json',JSON.stringify({schema:'pipeline.onboarding-consent-marker.v1',status:'consent-given-onboarding-incomplete',consentGivenAt:'2026-09-28T00:00:00.000Z'}));const before=files(f.root);assert.equal(f.controller.observe({rootDir:f.root}).state,'active');assert.equal(readGovernanceEnrollmentRetirement({rootDir:f.root}),null);assert.deepEqual(files(f.root),before);put(f.root,'.agent-pipeline/onboarding-consent.json','{}');assert.equal(f.controller.observe({rootDir:f.root}).state,'inactive');const retained=files(f.base);assert.throws(()=>readGovernanceEnrollmentRetirement({rootDir:f.root}),error=>error.code==='GS-NONGIT-RETAINED-HISTORY');assert.deepEqual(files(f.base),retained);});

test('canonical V3 owned projection qualifies existing enrollment without invented receipt; drift fails closed',t=>{
 const f=fixture(t);seedV3(f.root);const current=f.controller.observe({rootDir:f.root});assert.equal(current.state,'active',JSON.stringify(current));assert.equal(current.provenance.kind,'legacy-v3-owned-projection');put(f.root,'.claude/pipeline.yaml','broken: true\n');const bad=f.controller.observe({rootDir:f.root});assert.equal(bad.state,'unverifiable-active');assert.equal(bad.requiresEnforcement,true);const driftBytes=files(f.base);assert.throws(()=>readGovernanceEnrollmentRetirement({rootDir:f.root}),error=>error.code==='GS-NONGIT-RETAINED-HISTORY');assert.deepEqual(files(f.base),driftBytes);decide(f.controller,f.root,'decline');assert.equal(f.controller.observe({rootDir:f.root}).state,'declined');
 // A valid explicit decision outranks unrelated retirement artifacts, even
 // when retained legacy enrollment would otherwise require enforcement.
 const barrier=join(f.root,'.agent-pipeline/enrollment-git-creation-barrier.json');mkdirSync(barrier,{recursive:true});
 const before=files(f.base),declined=f.controller.observe({rootDir:f.root});
 assert.equal(declined.state,'declined');assert.equal(declined.requiresEnforcement,false);assert.equal(declined.hintAllowed,false);assert.deepEqual(files(f.base),before);
 rmSync(barrier,{recursive:true});
 const active=fixture(t,{git:true});decide(active.controller,active.root,'enroll');mkdirSync(join(active.root,'.agent-pipeline/enrollment-git-creation-barrier.json'),{recursive:true});
 const activeBefore=files(active.base),observed=active.controller.observe({rootDir:active.root});
 assert.equal(observed.state,'active');assert.equal(observed.requiresEnforcement,true);assert.deepEqual(files(active.base),activeBefore);
});

test('paired canonical legacy authority qualifies; malformed source paired with valid authority stays governed',t=>{const f=fixture(t);put(f.root,'.claude/pipeline.yaml',freshManifestBytes());put(f.root,'.claude/pipeline.json',freshCalibrationBytes());const initial=f.controller.observe({rootDir:f.root});assert.equal(initial.state,'active',JSON.stringify(initial));assert.equal(initial.provenance.kind,'legacy-paired-authority');put(f.root,'pipeline.user.yaml','schema: fabricated\n');assert.equal(f.controller.observe({rootDir:f.root}).state,'unverifiable-active');});

test('fabricated/cloned/stale plans cannot mutate storage; consumed plan cannot replay',t=>{const f=fixture(t,{git:true}),config=join(f.root,'.git','config');const plan=f.controller.planDecision({rootDir:f.root,decision:'decline',by:'Fixture'});assert.throws(()=>f.controller.applyDecision({...plan},{activate:true,planSha256:plan.planSha256}),/GS-PLAN/);writeFileSync(config,readFileSync(config,'utf8')+'# independent drift\n');assert.throws(()=>f.controller.applyDecision(plan,{activate:true,planSha256:plan.planSha256}),/GS-PREIMAGE-DRIFT/);const next=f.controller.planDecision({rootDir:f.root,decision:'decline',by:'Fixture'});f.controller.applyDecision(next,{activate:true,planSha256:next.planSha256});assert.throws(()=>f.controller.applyDecision(next,{activate:true,planSha256:next.planSha256}),/GS-PLAN/);assert.equal(existsSync(config+'.lock'),false);const fresh=fixture(t,{git:true}),freshPlan=fresh.controller.planDecision({rootDir:fresh.root,decision:'enroll',by:'Fixture'});put(fresh.root,'project/pipeline-state.json','{}');const snapshot=files(fresh.base);assert.throws(()=>fresh.controller.applyDecision(freshPlan,{activate:true,planSha256:freshPlan.planSha256}),/GS-HISTORY-DRIFT/);assert.deepEqual(files(fresh.base),snapshot);});

test('dedicated malformed record/mode/alias refuse authority; aliases do not cause outside content reads',t=>{const f=fixture(t);const active=decide(f.controller,f.root,'enroll'),record=join(f.host,active.scopeKey+'.json');chmodSync(record,0o644);assert.equal(f.controller.observe({rootDir:f.root}).state,'unverifiable-active');chmodSync(record,0o600);put(f.host,active.scopeKey+'.json','{}\n');assert.equal(f.controller.observe({rootDir:f.root}).state,'unverifiable-active');rmSync(record);const outside=join(f.base,'outside');writeFileSync(outside,'synthetic private sentinel');symlinkSync(outside,record);assert.equal(f.controller.observe({rootDir:f.root}).state,'unverifiable-active');assert.equal(readFileSync(outside,'utf8'),'synthetic private sentinel');});

test('root inode reuse invalidates bound record, oversized sparse record and hardlinks reject without adoption',t=>{const f=fixture(t);const active=decide(f.controller,f.root,'enroll'),record=join(f.host,active.scopeKey+'.json'),saved=join(f.base,'old-root');renameSync(f.root,saved);mkdirSync(f.root);assert.equal(f.controller.observe({rootDir:f.root}).state,'unverifiable-active');rmSync(f.root,{recursive:true});renameSync(saved,f.root);truncateSync(record,262145);assert.equal(f.controller.observe({rootDir:f.root}).state,'unverifiable-active');writeFileSync(record,'{}\n');linkSync(record,join(f.host,'second-link'));assert.equal(f.controller.observe({rootDir:f.root}).state,'unverifiable-active');});

test('authenticated onboarding projection reuses enrollment and explicit activation reverses decline',t=>{const f=fixture(t);assert.throws(()=>f.controller.recordOnboardingEnrollment({rootDir:f.root,activate:true}),/GS-ONBOARDING-PROVENANCE/);seedV3(f.root);const before=files(f.base);assert.equal(f.controller.recordOnboardingEnrollment({rootDir:f.root,activate:true}).state,'active');assert.deepEqual(files(f.base),before);assert.throws(()=>f.controller.recordOnboardingEnrollment({rootDir:f.root}),/GS-ONBOARDING-ACTIVATION/);decide(f.controller,f.root,'decline');assert.equal(f.controller.recordOnboardingEnrollment({rootDir:f.root,activate:true}).state,'active');const retained=fixture(t);seedV3(retained.root);decide(retained.controller,retained.root,'decline');put(retained.root,'project/pipeline-state.json','{}');const snapshot=files(retained.base);assert.throws(()=>retained.controller.recordOnboardingEnrollment({rootDir:retained.root,activate:true}),/GS-NONGIT-RETAINED-HISTORY/);assert.deepEqual(files(retained.base),snapshot);const git=fixture(t,{git:true});put(git.root,'.agent-pipeline/onboarding-consent.json',JSON.stringify({schema:'pipeline.onboarding-consent-marker.v1',status:'consent-given-onboarding-incomplete',consentGivenAt:'2026-09-28T00:00:00.000Z'}));decide(git.controller,git.root,'decline');assert.equal(decide(git.controller,git.root,'enroll').state,'declined');assert.equal(readGovernanceEnrollmentRetirement({rootDir:git.root}).phase,'pending');const pending=files(git.base);assert.equal(decide(git.controller,git.root,'enroll').state,'declined');assert.deepEqual(files(git.base),pending);seedV3(git.root);assert.throws(()=>git.controller.recordOnboardingEnrollment({rootDir:git.root,activate:true}));assert.equal(git.controller.observe({rootDir:git.root}).state,'declined');});

test('actual observations and absence errors satisfy closed published schema',t=>{const f=fixture(t);for(const observation of [f.controller.observe({rootDir:f.root}),f.controller.observe({rootDir:join(f.base,'absent')}),decide(f.controller,f.root,'decline')])assert.deepEqual(validateAgainstSchema(observation,scopeSchema).errors,[]);const spoof={...f.controller.observe({rootDir:f.root}),implementationAuthority:true};assert.ok(validateAgainstSchema(spoof,scopeSchema).errors.length>0);});

test('neutral V3 authority has precedence over retained runtime and no invented receipt is required',t=>{const f=fixture(t),manifest=seedV3(f.root);put(f.root,'project/pipeline.yaml',manifest);put(f.root,'.claude/pipeline.yaml','retained: stale\n');const observed=f.controller.observe({rootDir:f.root});assert.equal(observed.state,'active');assert.equal(observed.provenance.refs[1].path,'project/pipeline.yaml');put(f.root,'project/pipeline.yaml','broken: true\n');put(f.root,'.claude/pipeline.yaml',manifest);assert.equal(f.controller.observe({rootDir:f.root}).state,'unverifiable-active');});

test('broken physical Git control cannot be recast as non-Git enrollment',t=>{const f=fixture(t);mkdirSync(join(f.root,'.git'));const before=files(f.base),observation=f.controller.observe({rootDir:f.root});assert.equal(observation.repositoryKind,'unavailable');assert.equal(observation.hintAllowed,false);assert.ok(observation.diagnostics.includes('GS-GIT-UNAVAILABLE'));assert.throws(()=>f.controller.planDecision({rootDir:f.root,decision:'enroll',by:'Fixture'}),error=>error.code==='GS-GIT-UNAVAILABLE'&&error.topologyDiagnostic.reason==='unsupported-existing-control'&&error.topologyDiagnostic.boundary==='selected-root'&&error.topologyDiagnostic.ancestorDepth===0&&error.topologyDiagnostic.gitReportsNotRepository===true);assert.deepEqual(files(f.base),before);
 assert.equal(observation.state,'inactive');assert.equal(observation.requiresEnforcement,false);
 const separate=fixture(t);runGit(separate.root,['init','--separate-git-dir='+join(separate.base,'control')]);const separateBefore=files(separate.base),unsupported=separate.controller.observe({rootDir:separate.root});
 assert.equal(unsupported.state,'inactive');assert.equal(unsupported.requiresEnforcement,false);assert.equal(unsupported.hintAllowed,false);assert.ok(unsupported.diagnostics.includes('GS-GIT-UNAVAILABLE'));assert.deepEqual(files(separate.base),separateBefore);
 const host=fixture(t),control=join(host.root,'.git');mkdirSync(control);chmodSync(control,0o555);
 if(hasCodexGitControlMount(host.root)){
  const beforeHost=files(host.base),inactive=host.controller.observe({rootDir:host.root});assert.equal(inactive.state,'inactive');assert.equal(inactive.repositoryKind,'non-git');assert.deepEqual(validateAgainstSchema(inactive,scopeSchema).errors,[]);assert.equal(readGovernanceEnrollmentRetirement({rootDir:host.root}),null);assert.deepEqual(files(host.base),beforeHost);assert.equal(existsSync(host.host),false);
  const stale=host.controller.planDecision({rootDir:host.root,decision:'enroll',by:'Fixture explicit host enrollment'}),saved=join(host.base,'old-control');chmodSync(control,0o755);renameSync(control,saved);mkdirSync(control);chmodSync(control,0o555);const changed=files(host.base);assert.throws(()=>host.controller.applyDecision(stale,{activate:true,planSha256:stale.planSha256}),/GS-SCOPE-DRIFT/);assert.deepEqual(files(host.base),changed);
  assert.equal(decide(host.controller,host.root,'enroll').state,'active');assert.equal(createGovernanceScopeController({hostStateRoot:host.host}).observe({rootDir:host.root}).state,'active');assert.deepEqual(readdirSync(control),[]);assert.equal(decide(host.controller,host.root,'decline').state,'declined');assert.equal(createGovernanceScopeController({hostStateRoot:host.host}).observe({rootDir:host.root}).state,'declined');assert.equal(decide(host.controller,host.root,'enroll').state,'active');decide(host.controller,host.root,'decline');
  mkdirSync(join(host.root,'.claude','.runtime','agent-pipeline','onboarding'),{recursive:true,mode:0o700});put(host.root,'project/pipeline-state.json','{}');const retained=files(host.base),refusal=decide(host.controller,host.root,'enroll');assert.equal(refusal.status,'refused');assert.equal(refusal.code,'GS-HOST-MANAGED-RETAINED-HISTORY');assert.equal(host.controller.observe({rootDir:host.root}).state,'declined');assert.throws(()=>readGovernanceEnrollmentRetirement({rootDir:host.root}),/GS-HOST-MANAGED-RETAINED-HISTORY/);assert.deepEqual(files(host.base),retained);const recovery=governanceEnrollmentRecoveryAction({rootDir:host.root,runner:'codex'});assert.equal(recovery.kind,'external-operator');assert.equal(recovery.mutation,false);assert.ok(recovery.argv.includes('inspect'));assert.ok(!recovery.argv.includes('plan-enrollment-git-creation'));assert.ok(!recovery.argv.includes('apply'));
  seedV3(host.root);const projection=files(host.base);assert.throws(()=>host.controller.recordOnboardingEnrollment({rootDir:host.root,activate:true}),/GS-HOST-MANAGED-RETAINED-HISTORY/);assert.deepEqual(files(host.base),projection);assert.deepEqual(readdirSync(control),[]);
 }else{assert.equal(host.controller.observe({rootDir:host.root}).hintAllowed,false);}
 const nonempty=fixture(t);mkdirSync(join(nonempty.root,'.git'));put(nonempty.root,'.git/foreign','retained');chmodSync(join(nonempty.root,'.git'),0o555);assert.equal(hasCodexGitControlMount(nonempty.root),false);assert.throws(()=>nonempty.controller.planDecision({rootDir:nonempty.root,decision:'enroll',by:'Fixture'}),/GS-GIT-UNAVAILABLE/);const alias=fixture(t);symlinkSync(control,join(alias.root,'.git'),'dir');assert.equal(hasCodexGitControlMount(alias.root),false);assert.throws(()=>alias.controller.planDecision({rootDir:alias.root,decision:'enroll',by:'Fixture'}),/GS-GIT-UNAVAILABLE/);
 // Restore only the manufactured fixture directories for registered cleanup.
 chmodSync(control,0o755);chmodSync(join(nonempty.root,'.git'),0o755);
});

test('enrolled current Git root survives an unrelated removed registered worktree and can plan decline',t=>{
 const f=fixture(t,{git:true}),active=decide(f.controller,f.root,'enroll'),ghost=join(f.base,'removed-worktree');
 runGit(f.root,['worktree','add','--detach',ghost,'HEAD']);const config=readFileSync(join(f.root,'.git/config'),'utf8');rmSync(ghost,{recursive:true});
 const after=f.controller.observe({rootDir:f.root});assert.equal(after.state,'active');assert.equal(after.requiresEnforcement,true);assert.equal(after.root,active.root);assert.equal(after.scopeKey,active.scopeKey);assert.deepEqual(after.diagnostics,[]);assert.equal(readFileSync(join(f.root,'.git/config'),'utf8'),config);
 const plan=f.controller.planDecision({rootDir:f.root,decision:'decline',by:'Fixture'});assert.equal(plan.root,active.root);assert.equal(plan.scopeKey,active.scopeKey);assert.equal(plan.decision,'decline');assert.equal(readFileSync(join(f.root,'.git/config'),'utf8'),config);
});

test('declined current Git root survives an unrelated removed worktree without hints or enforcement and can re-enroll',t=>{
 const f=fixture(t,{git:true}),declined=decide(f.controller,f.root,'decline'),ghost=join(f.base,'removed-worktree');
 runGit(f.root,['worktree','add','--detach',ghost,'HEAD']);const config=readFileSync(join(f.root,'.git/config'),'utf8');rmSync(ghost,{recursive:true});
 const after=f.controller.observe({rootDir:f.root});assert.equal(after.state,'declined');assert.equal(after.requiresEnforcement,false);assert.equal(after.hintAllowed,false);assert.equal(after.scopeKey,declined.scopeKey);assert.deepEqual(after.diagnostics,[]);assert.equal(readFileSync(join(f.root,'.git/config'),'utf8'),config);
 const plan=f.controller.planDecision({rootDir:f.root,decision:'enroll',by:'Fixture'});assert.equal(plan.scopeKey,declined.scopeKey);const active=f.controller.applyDecision(plan,{activate:true,planSha256:plan.planSha256});assert.equal(active.state,'active');
});

test('closest containing nested linked worktree keeps its own decision despite a stale sibling',t=>{
 const f=fixture(t,{git:true}),linked=join(f.root,'nested'),ghost=join(f.base,'removed-worktree');runGit(f.root,['worktree','add','--detach',linked,'HEAD']);runGit(f.root,['worktree','add','--detach',ghost,'HEAD']);
 decide(f.controller,f.root,'enroll');const declined=decide(f.controller,linked,'decline');const child=join(linked,'child');mkdirSync(child);rmSync(ghost,{recursive:true});
 const observed=f.controller.observe({rootDir:child});assert.equal(observed.root,linked);assert.equal(observed.scopeKey,declined.scopeKey);assert.equal(observed.state,'declined');assert.equal(f.controller.observe({rootDir:f.root}).state,'active');
});

test('path-component containment does not select a prefix sibling and selected alias paths cannot authorize decisions',t=>{
 const f=fixture(t,{git:true}),sibling=f.root+'-sibling';runGit(f.root,['worktree','add','--detach',sibling,'HEAD']);decide(f.controller,f.root,'enroll');decide(f.controller,sibling,'decline');
 const child=join(f.root,'child');mkdirSync(child);assert.equal(f.controller.observe({rootDir:child}).root,f.root);assert.equal(f.controller.observe({rootDir:sibling}).root,sibling);
 const alias=join(f.base,'root-alias');symlinkSync(f.root,alias);const before=readFileSync(join(f.root,'.git/config'),'utf8');assert.throws(()=>f.controller.planDecision({rootDir:alias,decision:'decline',by:'Fixture'}),/GS-ALIAS/);const refused=f.controller.observe({rootDir:alias});assert.equal(refused.hintAllowed,false);assert.ok(refused.diagnostics.includes('GS-ALIAS'));assert.equal(readFileSync(join(f.root,'.git/config'),'utf8'),before);
 assert.equal(refused.state,'unverifiable-active');assert.equal(refused.requiresEnforcement,true);assert.equal(refused.root,f.root);
 const declinedAlias=join(f.base,'declined-alias');symlinkSync(sibling,declinedAlias);const declined=f.controller.observe({rootDir:declinedAlias});
 assert.equal(declined.state,'declined');assert.equal(declined.requiresEnforcement,false);assert.equal(declined.hintAllowed,false);
 // Another controller records a real decline. This controller learns it only
 // through the root alias, then loses access to both config and private proof.
 const remembered=fixture(t,{git:true});decide(remembered.controller,remembered.root,'enroll');assert.equal(remembered.controller.observe({rootDir:remembered.root}).state,'active');
 decide(createGovernanceScopeController({hostStateRoot:remembered.host}),remembered.root,'decline');const rememberedAlias=join(remembered.base,'root-alias');symlinkSync(remembered.root,rememberedAlias);
 const throughAlias=remembered.controller.observe({rootDir:rememberedAlias});assert.equal(throughAlias.state,'declined');assert.equal(throughAlias.requiresEnforcement,false);assert.equal(throughAlias.hintAllowed,false);assert.deepEqual(throughAlias.diagnostics,['GS-ALIAS']);
 linkSync(join(remembered.root,'.git/config'),join(remembered.base,'config-hardlink'));const savedHost=join(remembered.base,'host-original');renameSync(remembered.host,savedHost);symlinkSync(savedHost,remembered.host);
 const rootBytes=files(remembered.root),proofBytes=files(savedHost),damaged=remembered.controller.observe({rootDir:remembered.root});assert.equal(damaged.state,'inactive','a valid decline learned through alias must clear the stale positive witness');assert.equal(damaged.requiresEnforcement,false);assert.equal(damaged.hintAllowed,false);assert.deepEqual(files(remembered.root),rootBytes);assert.deepEqual(files(savedHost),proofBytes);
 if(process.platform!=='win32'){const wrongCase=join(f.base,'Repo');assert.throws(()=>f.controller.planDecision({rootDir:wrongCase,decision:'decline',by:'Fixture'}));assert.equal(f.controller.observe({rootDir:wrongCase}).hintAllowed,false);assert.equal(readFileSync(join(f.root,'.git/config'),'utf8'),before);}
});

test('removed relevant linked directory remains unavailable and cannot be used to plan a decision',t=>{
 const f=fixture(t,{git:true}),linked=join(f.base,'linked');runGit(f.root,['worktree','add','--detach',linked,'HEAD']);decide(f.controller,linked,'enroll');const config=readFileSync(join(f.root,'.git/config'),'utf8');rmSync(linked,{recursive:true});
 const observed=f.controller.observe({rootDir:linked});assert.equal(observed.root,null);assert.equal(observed.repositoryKind,'unavailable');assert.equal(observed.hintAllowed,false);assert.throws(()=>f.controller.planDecision({rootDir:linked,decision:'decline',by:'Fixture'}));assert.equal(readFileSync(join(f.root,'.git/config'),'utf8'),config);
});

test('current Git root inode replacement retains record binding refusal rather than inactive admission',t=>{
 const f=fixture(t,{git:true});decide(f.controller,f.root,'enroll');const saved=join(f.base,'old-root');renameSync(f.root,saved);mkdirSync(f.root);renameSync(join(saved,'.git'),join(f.root,'.git'));
 const before=readFileSync(join(f.root,'.git/config'),'utf8'),observed=f.controller.observe({rootDir:f.root});assert.equal(observed.state,'unverifiable-active');assert.equal(observed.requiresEnforcement,true);assert.ok(observed.diagnostics.includes('GS-RECORD-BINDING'));assert.throws(()=>f.controller.planDecision({rootDir:f.root,decision:'decline',by:'Fixture'}),/GS-RECORD-BINDING/);assert.equal(readFileSync(join(f.root,'.git/config'),'utf8'),before);
});

test('owned Git config alias and hardlink refuse active authority and cannot become inactive admission',t=>{
 const f=fixture(t,{git:true});decide(f.controller,f.root,'enroll');const config=join(f.root,'.git/config'),outside=join(f.base,'config-copy');renameSync(config,outside);symlinkSync(outside,config);
 const original=readFileSync(outside,'utf8'),alias=createGovernanceScopeController({hostStateRoot:f.host}).observe({rootDir:f.root});assert.equal(alias.state,'unverifiable-active');assert.equal(alias.requiresEnforcement,true);assert.equal(alias.hintAllowed,false);assert.throws(()=>f.controller.planDecision({rootDir:f.root,decision:'decline',by:'Fixture'}));assert.equal(readFileSync(outside,'utf8'),original);
 rmSync(config);renameSync(outside,config);linkSync(config,outside);const linked=createGovernanceScopeController({hostStateRoot:f.host}).observe({rootDir:f.root});assert.equal(linked.state,'unverifiable-active');assert.equal(linked.requiresEnforcement,true);assert.ok(linked.diagnostics.includes('GS-CONFIG-UNAVAILABLE'));assert.equal(readFileSync(config,'utf8'),original);
 const proof=join(f.host,linked.scopeKey+'.git-proof.json'),proofBytes=readFileSync(proof);chmodSync(proof,0o644);let snapshot=files(f.base),invalid=createGovernanceScopeController({hostStateRoot:f.host}).observe({rootDir:f.root});assert.equal(invalid.state,'unverifiable-active');assert.deepEqual(invalid.diagnostics,['GS-POSITIVE-PROOF']);assert.deepEqual(files(f.base),snapshot);chmodSync(proof,0o600);writeFileSync(proof,'invalid-json');snapshot=files(f.base);invalid=createGovernanceScopeController({hostStateRoot:f.host}).observe({rootDir:f.root});assert.equal(invalid.state,'unverifiable-active');assert.deepEqual(invalid.diagnostics,['GS-POSITIVE-PROOF']);assert.deepEqual(files(f.base),snapshot);writeFileSync(proof,proofBytes);linkSync(proof,proof+'.second-link');invalid=createGovernanceScopeController({hostStateRoot:f.host}).observe({rootDir:f.root});assert.equal(invalid.state,'unverifiable-active');assert.deepEqual(invalid.diagnostics,['GS-POSITIVE-PROOF']);
 // A global store alias proves no claim for a fresh controller. A controller
 // which actually validated this root/common enrollment can retain diagnostic
 // enforcement while both current config and independent proof are damaged.
 const known=fixture(t,{git:true});decide(known.controller,known.root,'enroll');assert.equal(known.controller.observe({rootDir:known.root}).state,'active');
 const knownConfig=join(known.root,'.git/config'),configLink=join(known.base,'config-hardlink');linkSync(knownConfig,configLink);
 const stored=join(known.base,'host-original');renameSync(known.host,stored);symlinkSync(stored,known.host);
 const aliasBytes=files(known.root),savedStore=files(stored),sameController=known.controller.observe({rootDir:known.root});
 assert.equal(sameController.state,'unverifiable-active','historically validated enrollment cannot silently become inactive after global proof-store alias');assert.equal(sameController.requiresEnforcement,true);assert.equal(sameController.hintAllowed,false);assert.deepEqual(files(known.root),aliasBytes);assert.deepEqual(files(stored),savedStore);
 assert.equal(sameController.provenance.kind,'none','diagnostic history is not a current decision authority');assert.throws(()=>known.controller.planDecision({rootDir:known.root,decision:'decline',by:'Fixture'}),error=>error.code==='GS-CONFIG-UNAVAILABLE');
 const freshUnknown=createGovernanceScopeController({hostStateRoot:known.host}).observe({rootDir:known.root});assert.equal(freshUnknown.state,'inactive','fresh observer cannot infer enrollment through globally aliased unreadable store and unreadable config');assert.equal(freshUnknown.requiresEnforcement,false);assert.equal(freshUnknown.hintAllowed,false);
 rmSync(known.host);const noProof=createGovernanceScopeController({hostStateRoot:known.host}).observe({rootDir:known.root});assert.equal(noProof.state,'inactive');assert.equal(noProof.requiresEnforcement,false);assert.equal(known.controller.observe({rootDir:known.root}).state,'unverifiable-active','same validated history remains diagnostic when the host proof directory is absent');symlinkSync(stored,known.host);
 rmSync(configLink);rmSync(known.host);renameSync(stored,known.host);assert.equal(decide(known.controller,known.root,'decline').state,'declined');renameSync(known.host,stored);symlinkSync(stored,known.host);linkSync(knownConfig,configLink);
 const afterDecline=known.controller.observe({rootDir:known.root});assert.equal(afterDecline.state,'inactive','a validated decline clears the diagnostic positive witness');assert.equal(afterDecline.requiresEnforcement,false);rmSync(configLink);assert.equal(known.controller.observe({rootDir:known.root}).state,'declined','usable current decline outranks historical proof/store damage');
 const replaced=fixture(t,{git:true});decide(replaced.controller,replaced.root,'enroll');const oldRoot=join(replaced.base,'old-root');renameSync(replaced.root,oldRoot);mkdirSync(replaced.root);renameSync(join(oldRoot,'.git'),join(replaced.root,'.git'));linkSync(join(replaced.root,'.git/config'),join(replaced.base,'changed-root-config'));const oldHost=join(replaced.base,'old-host');renameSync(replaced.host,oldHost);symlinkSync(oldHost,replaced.host);assert.equal(replaced.controller.observe({rootDir:replaced.root}).requiresEnforcement,false,'diagnostic witness cannot adopt a replacement root identity');
 const commonReplaced=fixture(t,{git:true});decide(commonReplaced.controller,commonReplaced.root,'enroll');const oldCommon=join(commonReplaced.base,'old-common');renameSync(join(commonReplaced.root,'.git'),oldCommon);cpSync(oldCommon,join(commonReplaced.root,'.git'),{recursive:true});linkSync(join(commonReplaced.root,'.git/config'),join(commonReplaced.base,'changed-common-config'));const replacedHost=join(commonReplaced.base,'old-host');renameSync(commonReplaced.host,replacedHost);symlinkSync(replacedHost,commonReplaced.host);assert.equal(commonReplaced.controller.observe({rootDir:commonReplaced.root}).requiresEnforcement,false,'diagnostic witness cannot adopt a replacement common identity');
 const foreign=fixture(t,{git:true}),foreignConfig=join(foreign.root,'.git/config');mkdirSync(foreign.host);const foreignStore=join(foreign.base,'foreign-host');renameSync(foreign.host,foreignStore);symlinkSync(foreignStore,foreign.host);linkSync(foreignConfig,join(foreign.base,'foreign-config-hardlink'));const never=foreign.controller.observe({rootDir:foreign.root});assert.equal(never.state,'inactive');assert.equal(never.requiresEnforcement,false);assert.equal(never.hintAllowed,false);
});

test('broken relevant linked Git control and unreadable owned config remain fail-closed',t=>{
 const f=fixture(t,{git:true}),linked=join(f.base,'linked');decide(f.controller,f.root,'enroll');runGit(f.root,['worktree','add','--detach',linked,'HEAD']);decide(f.controller,linked,'enroll');const linkedControl=readFileSync(join(linked,'.git')),commonConfig=readFileSync(join(f.root,'.git/config'),'utf8');put(linked,'.git','gitdir: '+join(f.base,'missing-control')+'\n');
 const beforeBroken=files(f.base),broken=createGovernanceScopeController({hostStateRoot:f.host}).observe({rootDir:linked});assert.equal(broken.state,'unverifiable-active');assert.equal(broken.requiresEnforcement,true);assert.equal(broken.hintAllowed,false);assert.ok(broken.diagnostics.includes('GS-GIT-UNAVAILABLE'));assert.deepEqual(files(f.base),beforeBroken);assert.throws(()=>f.controller.planDecision({rootDir:linked,decision:'decline',by:'Fixture'}),/GS-GIT-UNAVAILABLE/);assert.equal(readFileSync(join(f.root,'.git/config'),'utf8'),commonConfig);
 writeFileSync(join(linked,'.git'),linkedControl);decide(f.controller,linked,'decline');put(linked,'.git','gitdir: '+join(f.base,'missing-control')+'\n');const declined=createGovernanceScopeController({hostStateRoot:f.host}).observe({rootDir:linked});assert.equal(declined.state,'declined');assert.equal(declined.requiresEnforcement,false);assert.equal(declined.hintAllowed,false);
 const config=join(f.root,'.git/config');renameSync(config,config+'.saved');mkdirSync(config);const unreadable=createGovernanceScopeController({hostStateRoot:f.host}).observe({rootDir:f.root});assert.equal(unreadable.state,'unverifiable-active');assert.equal(unreadable.requiresEnforcement,true);assert.equal(unreadable.hintAllowed,false);assert.throws(()=>f.controller.planDecision({rootDir:f.root,decision:'enroll',by:'Fixture'}));
 rmSync(config,{recursive:true});renameSync(config+'.saved',config);chmodSync(config,0o000);
 // chmod(000) is genuinely unreadable under an ordinary OS user. Root may
 // bypass permissions, so do not fabricate an EACCES observation there.
 let blocked=false;try{readFileSync(config);}catch(error){blocked=error.code==='EACCES';}
 const permission=createGovernanceScopeController({hostStateRoot:f.host}).observe({rootDir:f.root});assert.equal(permission.requiresEnforcement,true);if(blocked)assert.equal(permission.state,'unverifiable-active');t.diagnostic('chmod(000) actual EACCES: '+blocked);chmodSync(config,0o644);
});

import {cpSync} from 'node:fs';
test('Git common-directory inode replacement invalidates enrollment without changing its record bytes',t=>{
 const f=fixture(t,{git:true});decide(f.controller,f.root,'enroll');const common=join(f.root,'.git'),saved=join(f.base,'old-common');renameSync(common,saved);cpSync(saved,common,{recursive:true});
 const before=readFileSync(join(common,'config'),'utf8'),observed=f.controller.observe({rootDir:f.root});assert.equal(observed.state,'unverifiable-active');assert.equal(observed.requiresEnforcement,true);assert.ok(observed.diagnostics.includes('GS-RECORD-BINDING'));assert.throws(()=>f.controller.planDecision({rootDir:f.root,decision:'decline',by:'Fixture'}),/GS-RECORD-BINDING/);assert.equal(readFileSync(join(common,'config'),'utf8'),before);
});

// Each original sibling callback is registered individually; no envelope case.
if (completionCases.length !== 23) throw new Error("Required completion declared case count drift");
const completionFd = process.env.PIPELINE_VERIFY_CASE_COMPLETION_FD === undefined
  ? openCompletionDescriptor(process.platform === "win32" ? "NUL" : "/dev/null", "w")
  : Number(process.env.PIPELINE_VERIFY_CASE_COMPLETION_FD);
registerTestCaseCompletion({ cases: completionCases, fd: completionFd,
  maxBytes: Number(process.env.PIPELINE_VERIFY_CASE_COMPLETION_MAX_BYTES ?? "65536") });
