// SPDX-License-Identifier: SUL-1.0
import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createGovernanceExportOutbox, enqueueGovernanceExport } from "./governance-export-outbox.mjs";
import { loadGovernanceExportOutbox, persistGovernanceExportOutbox } from "./governance-export-outbox-store.mjs";
const revision = "a".repeat(64); const item = { schema: "pipeline.governance-export-event.v1", destinationEventId: "b".repeat(64), destinationProfile: "test-siem", format: "ndjson", policyRevision: revision, sourceEventDigest: "c".repeat(64), fields: { eventId: "event-1" } };
const second = { ...item, destinationEventId: "d".repeat(64), sourceEventDigest: "e".repeat(64) }; const replacement = { ...item, destinationEventId: "f".repeat(64), sourceEventDigest: "0".repeat(64) };
test("persists one destination outbox with an exact preimage and reloads it", async () => { const root = mkdtempSync(join(tmpdir(), "export-outbox-store-")); const absent = await loadGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision }); const next = enqueueGovernanceExport(absent.outbox, item); const stored = await persistGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision, expectedSha256: absent.sha256, outbox: next }); const loaded = await loadGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision }); assert.equal(stored.status, "stored"); assert.equal(loaded.outbox.entries.length, 1); assert.equal(loaded.sha256, stored.sha256); });
test("does not overwrite a changed outbox from a stale preimage", async () => { const root = mkdtempSync(join(tmpdir(), "export-outbox-store-")); const first = await loadGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision }); const next = enqueueGovernanceExport(first.outbox, item); await persistGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision, expectedSha256: null, outbox: next }); const stale = await persistGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision, expectedSha256: null, outbox: createGovernanceExportOutbox({ destinationProfile: "test-siem", policyRevision: revision }) }); assert.equal(stale.status, "conflict"); });
test("stores an append that keeps every already stored entry unchanged", async () => { const root = mkdtempSync(join(tmpdir(), "export-outbox-store-")); const absent = await loadGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision }); await persistGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision, expectedSha256: absent.sha256, outbox: enqueueGovernanceExport(absent.outbox, item) }); const loaded = await loadGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision }); const stored = await persistGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision, expectedSha256: loaded.sha256, outbox: enqueueGovernanceExport(loaded.outbox, second) }); const reloaded = await loadGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision }); assert.equal(stored.status, "stored"); assert.equal(reloaded.outbox.entries.length, 2); });
test("refuses a shrunk outbox and leaves the stored outbox byte-identical", async () => { const root = mkdtempSync(join(tmpdir(), "export-outbox-store-")); const absent = await loadGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision }); const first = await persistGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision, expectedSha256: absent.sha256, outbox: enqueueGovernanceExport(absent.outbox, item) }); const one = await loadGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision }); await persistGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision, expectedSha256: first.sha256, outbox: enqueueGovernanceExport(one.outbox, second) }); const before = await loadGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision }); const shrunk = { ...before.outbox, entries: [before.outbox.entries[0]] }; await assert.rejects(persistGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision, expectedSha256: before.sha256, outbox: shrunk }), { code: "GEOS-TRUNCATION" }); const after = await loadGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision }); assert.equal(before.outbox.entries.length, 2); assert.equal(after.sha256, before.sha256); assert.equal(after.outbox.entries.length, 2); });
test("refuses an outbox whose already stored projection was replaced", async () => { const root = mkdtempSync(join(tmpdir(), "export-outbox-store-")); const absent = await loadGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision }); await persistGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision, expectedSha256: absent.sha256, outbox: enqueueGovernanceExport(absent.outbox, item) }); const before = await loadGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision }); const mutated = { ...before.outbox, entries: [{ ...before.outbox.entries[0], projection: replacement }] }; await assert.rejects(persistGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision, expectedSha256: before.sha256, outbox: mutated }), { code: "GEOS-TRUNCATION" }); const after = await loadGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision }); assert.equal(after.sha256, before.sha256); assert.equal(after.outbox.entries[0].projection.destinationEventId, item.destinationEventId); });
test("exempts the first write into an absent outbox from the truncation check", async () => { const root = mkdtempSync(join(tmpdir(), "export-outbox-store-")); const absent = await loadGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision }); assert.equal(absent.status, "absent"); assert.equal(absent.sha256, null); const stored = await persistGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision, expectedSha256: null, outbox: enqueueGovernanceExport(absent.outbox, item) }); assert.equal(stored.status, "stored"); });
test("reports a stale preimage as a conflict even when the write would also truncate", async () => { const root = mkdtempSync(join(tmpdir(), "export-outbox-store-")); const absent = await loadGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision }); const first = await persistGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision, expectedSha256: absent.sha256, outbox: enqueueGovernanceExport(absent.outbox, item) }); const one = await loadGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision }); await persistGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision, expectedSha256: first.sha256, outbox: enqueueGovernanceExport(one.outbox, second) }); const stale = await persistGovernanceExportOutbox({ repositoryRoot: root, destinationProfile: "test-siem", policyRevision: revision, expectedSha256: first.sha256, outbox: one.outbox }); assert.equal(stale.status, "conflict"); });
