#!/usr/bin/env node
// SPDX-License-Identifier: SUL-1.0
import assert from "node:assert/strict";
import { computeEffectiveCapacity, createLocalWorkerPool, localWorkerPoolDigest, reduceLocalWorkerPool, selectLocalWorkerPoolReferenceAdapter, validateLocalWorkerPool } from "./local-worker-pool.mjs";

const A = "a".repeat(64), B = "b".repeat(64), C = "c".repeat(64), O = "1".repeat(40);
const bounds = (certified = 3, pressure = 5) => ({ configured:{concurrentTasks:8,required:true}, operator:{concurrentTasks:6,required:true}, certified:{concurrentTasks:certified,required:true}, observed:{concurrentTasks:4,required:true}, pressure:{concurrentTasks:pressure,required:false}, reserved:{elephant:1,verify:1,critic:0}, effective:{status:"available",concurrentTasks:Math.max(0,Math.min(8,6,certified,4,pressure)-2),reasonCodes:[]} });
const worker = (subject = A, leaseId = "lease-1") => ({ subjectSha256:subject, workspaceLease:{leaseId,subjectSha256:subject,repository:A,baseCommit:O,candidateCommit:O,worktreePathSha256:B,writePaths:["lib/pool.mjs"],ownerNonce:"owner-1",issuedMonotonicMs:0,expiresMonotonicMs:60000,cleanupState:"active",evidenceSha256:C}, process:{identitySha256:B,separation:"observed",assuranceEvidenceSha256:C}, heartbeat:{intervalMs:1000,orphanAfterMs:3000,lastObservedMonotonicMs:0,evidenceSha256:C}, state:"running",lastTransitionMonotonicMs:0,stateEvidenceSha256:C });
const pool = () => createLocalWorkerPool({ poolId:"pool-1",candidate:{repositorySha256:A,baseCommit:O,candidateCommit:O},queueRevision:0,capacity:bounds(),workers:[worker()],admissionSet:[{taskId:"task-1",subjectSha256:A,requestSha256:B,baseCommit:O,candidateCommit:O,writePaths:["lib/pool.mjs"],state:"admitted"}],cleanupOwner:{subjectSha256:A,ownerNonce:"owner-1",evidenceSha256:C},serialFallback:true });
let passed = 0; const check = (name, fn) => { fn(); passed += 1; console.log(`PASS LWP${String(passed).padStart(2,"0")} ${name}`); };
const event = (kind, extra = {}) => ({ kind,subjectSha256:A,candidateCommit:O,monotonicMs:1000,evidenceSha256:B,...extra });
check("calculates minimum known capacity after Elephant, Verify, and Critic reservation", () => { assert.deepEqual(computeEffectiveCapacity(bounds()), {status:"available",concurrentTasks:1,reasonCodes:[]}); assert.deepEqual(computeEffectiveCapacity(bounds(3,2)), {status:"available",concurrentTasks:0,reasonCodes:[]}); assert.deepEqual(computeEffectiveCapacity({...bounds(),certified:{concurrentTasks:null,required:true}}), {status:"unavailable",concurrentTasks:null,reasonCodes:["UNKNOWN:certified"]}); });
check("creates a frozen closed contract with portable workspace leases and no isolation claim", () => { const value = pool(); assert.equal(validateLocalWorkerPool(value).ok, true); assert.equal(localWorkerPoolDigest(value).length, 64); assert.equal(Object.isFrozen(value), true); });
check("projects serial and in-process reference adapters without starting a worker", () => { const value=pool(); assert.deepEqual(selectLocalWorkerPoolReferenceAdapter(value,"serial"),{status:"available",kind:"serial",concurrentTasks:1,reasonCode:null}); assert.equal(selectLocalWorkerPoolReferenceAdapter(value,"in-process").reasonCode,"UNAVAILABLE:parallel-admission"); const parallel=structuredClone(value); parallel.serialFallback=false; assert.equal(selectLocalWorkerPoolReferenceAdapter(parallel,"in-process").concurrentTasks,1); });
check("rejects path escape, relational heartbeat/lease drift, stale owner, foreign workspace and capacity over-admission", () => { const value = pool(); const malformed = structuredClone(value); malformed.workers[0].workspaceLease.writePaths=["../escape"]; assert.equal(validateLocalWorkerPool(malformed).ok, false); malformed.workers[0].workspaceLease.writePaths=["lib/pool.mjs"]; malformed.workers[0].heartbeat.orphanAfterMs=2999; assert.equal(validateLocalWorkerPool(malformed).ok, false); malformed.workers[0].heartbeat.orphanAfterMs=3000; malformed.workers[0].workspaceLease.expiresMonotonicMs=0; assert.equal(validateLocalWorkerPool(malformed).ok, false); malformed.workers[0].workspaceLease.expiresMonotonicMs=60000; malformed.cleanupOwner.ownerNonce="stale"; assert.equal(validateLocalWorkerPool(malformed).code,"STALE:cleanup-owner"); malformed.cleanupOwner.ownerNonce="owner-1"; malformed.workers[0].workspaceLease.candidateCommit="2".repeat(40); assert.equal(validateLocalWorkerPool(malformed).code,"AUTHORITY:workspace-binding"); const duplicate = structuredClone(value); duplicate.workers.push(worker(A,"lease-2")); duplicate.serialFallback=false; assert.equal(validateLocalWorkerPool(duplicate).ok, false); });
check("models heartbeat, cancellation, timeout, orphan recovery and completion only as synthetic state", () => { let value = pool(); value = reduceLocalWorkerPool(value,event("heartbeat")).pool; assert.equal(value.workers[0].heartbeat.lastObservedMonotonicMs,1000); value = reduceLocalWorkerPool(value,event("cancel")).pool; assert.equal(value.workers[0].state,"cancel-requested"); assert.equal(reduceLocalWorkerPool(value,event("cancelled",{monotonicMs:1001})).pool.workers[0].state,"cancelled"); assert.equal(reduceLocalWorkerPool(pool(),event("completed")).pool.workers[0].state,"completed"); assert.equal(reduceLocalWorkerPool(pool(),event("timeout")).pool.workers[0].state,"timed-out"); assert.equal(reduceLocalWorkerPool(pool(),event("orphan-suspected")).code,"BOUND:orphan-deadline"); let orphan = reduceLocalWorkerPool(pool(),event("orphan-suspected",{monotonicMs:3000})).pool; orphan = reduceLocalWorkerPool(orphan,event("recovered",{monotonicMs:3001})).pool; assert.equal(orphan.workers[0].state,"recovered"); });
check("invalidates stale candidates and leaves result import unavailable until B1-I authority exists", () => { const value=pool(); assert.equal(reduceLocalWorkerPool(value,event("heartbeat",{candidateCommit:"2".repeat(40)})).code,"STALE:candidate"); const stale=reduceLocalWorkerPool(value,event("stale-candidate",{candidateCommit:"2".repeat(40)})); assert.equal(stale.pool.workers[0].state,"rejected"); assert.equal(stale.pool.admissionSet[0].state,"invalidated"); assert.equal(reduceLocalWorkerPool(value,event("result-import")).code,"UNAVAILABLE:result-import-authority"); });
console.log(`${passed}/6 checks passed.`);
