// SPDX-License-Identifier: SUL-1.0
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { buildLocalProvenance } from "./provenance-local-builder.mjs";

const hash = (letter) => letter.repeat(64);
const root = mkdtempSync(join(tmpdir(), "provenance-builder-"));
mkdirSync(join(root, "dist"));
writeFileSync(join(root, "package-lock.json"), "lock\n");
writeFileSync(join(root, "plugin.json"), "plugin\n");
execFileSync("git", ["-C", root, "init", "-q"]);
execFileSync("git", ["-C", root, "add", "package-lock.json", "plugin.json"]);
execFileSync("git", ["-C", root, "-c", "user.email=provenance@example.test", "-c", "user.name=Provenance Test", "commit", "-qm", "source"]);
writeFileSync(join(root, "dist", "plugin.tgz"), "artifact\n");
const candidate = { commit: execFileSync("git", ["-C", root, "rev-parse", "HEAD"], { encoding: "utf8" }).trim(), tree: execFileSync("git", ["-C", root, "rev-parse", "HEAD^{tree}"], { encoding: "utf8" }).trim() };
const input = { root, artifact: { id: "plugin.tgz", path: "dist/plugin.tgz" }, candidate, materials: ["plugin.json", "package-lock.json"], builder: { id: "local-reference", digest: hash("c") }, invocation: { id: "pack", parametersSha256: hash("d") }, environment: { kind: "test", identitySha256: hash("e") }, reproducibility: "repeatable-in-same-builder", existing: [] };
const first = buildLocalProvenance(input);
const second = buildLocalProvenance(input);
assert.equal(first.ok, true);
assert.deepEqual(first, second);
assert.deepEqual(first.envelope.materials.map((entry) => entry.id), ["package-lock.json", "plugin.json"]);
assert.equal(first.envelope.assurance, "unverified");
assert.equal(first.envelope.reproducibility, "repeatable-in-same-builder");
assert.equal(buildLocalProvenance({ ...input, candidate: { ...candidate, tree: "a".repeat(40) } }).code, "PROVENANCE-BUILDER-CANDIDATE-MISMATCH");
assert.equal(buildLocalProvenance({ ...input, reproducibility: "claimed" }).code, "PROVENANCE-BUILDER-INPUT-INVALID");
assert.equal(buildLocalProvenance({ ...input, materials: ["package-lock.json", "./package-lock.json"] }).code, "PROVENANCE-BUILDER-FILE-INVALID");
assert.equal(buildLocalProvenance({ ...input, artifact: { ...input.artifact, path: "../outside" } }).code, "PROVENANCE-BUILDER-FILE-INVALID");
assert.equal(buildLocalProvenance({ ...input, materials: ["missing"] }).code, "PROVENANCE-BUILDER-FILE-INVALID");
writeFileSync(join(root, "plugin.json"), "changed source\n");
assert.equal(buildLocalProvenance(input).code, "PROVENANCE-BUILDER-FILE-INVALID");
execFileSync("git", ["-C", root, "add", "plugin.json"]);
assert.equal(buildLocalProvenance(input).code, "PROVENANCE-BUILDER-FILE-INVALID");
writeFileSync(join(root, "plugin.json"), "plugin\n");
execFileSync("git", ["-C", root, "add", "plugin.json"]);
writeFileSync(join(root, "dist", "plugin.tgz"), "changed artifact\n");
assert.equal(buildLocalProvenance({ ...input, existing: [first.envelope] }).code, "PROVENANCE-SUBJECT-REUSE");
console.log("provenance local-builder checks passed");
