// SPDX-License-Identifier: SUL-1.0
import assert from "node:assert/strict";
import { bindSbomRelease, buildSbomAuditBundle } from "./sbom-release-binding.mjs";
let passed = 0; function test(name, fn) { try { fn(); passed += 1; console.log(`PASS ${name}`); } catch (error) { console.error(`FAIL ${name}: ${error.message}`); process.exitCode = 1; } }
const digest = "a".repeat(64); const manifest = { schema: "pipeline.sbom-manifest.v1", candidate: { repositoryFingerprint: "repo", commit: "c", tree: "t" }, sourceInputs: [{ path: "lock", sha256: "b".repeat(64) }], adapter: { id: "node", version: "1", configSha256: "c".repeat(64) }, formats: [{ format: "cyclonedx-json", profile: "CycloneDX-1.6", payloadSha256: "d".repeat(64) }, { format: "spdx-json", profile: "SPDX-2.3", payloadSha256: "e".repeat(64) }], components: [{ id: "a", scope: "s", provenance: "p", relationships: [] }], completeness: { status: "complete", declared: 1, observed: 1 }, freshness: { status: "fresh", candidateMatches: true, sourceInputsMatch: true }, privacy: { classification: "public", exportPolicy: "public-redacted" }, payload: { canonicalSha256: digest, formats: { "cyclonedx-json": { profile: "CycloneDX-1.6", sha256: "d".repeat(64) }, "spdx-json": { profile: "SPDX-2.3", sha256: "e".repeat(64) } } }, lifecycle: { state: "complete", code: "SBOM-COMPLETE" } }; const input = (release, components = ["a"]) => ({ release, manifest: { ...manifest, components: components.map((id) => ({ ...manifest.components[0], id })) }, validation: { valid: true, digest } });
test("binds an immutable release and computes the next delta", () => { const first = bindSbomRelease([], input("1.0.0", ["a", "b"])); const second = bindSbomRelease(first.history, input("1.1.0", ["b", "c"])); assert.deepEqual(second.entry.delta, { added: ["c"], removed: ["a"] }); assert.equal(bindSbomRelease(second.history, input("1.1.0", ["b"])).code, "SBOM-RELEASE-IMMUTABLE"); });
test("rejects stale, partial or invalid release inputs", () => { assert.equal(bindSbomRelease([], { ...input("1.0.0", ["a"]), manifest: { ...manifest, freshness: { status: "stale" } } }).ok, false); assert.equal(bindSbomRelease([], { ...input("1.0.0", ["a"]), validation: { valid: false } }).code, "SBOM-RELEASE-PRECONDITION"); });
test("audit bundle contains all required digest references only", () => { const links = Object.fromEntries(["sbom", "policy", "completeness", "validation", "releaseBinding"].map((key) => [key, { schema: `pipeline.${key}.v1`, digest }])); const bundle = buildSbomAuditBundle(links); assert.equal(bundle.ok, true); assert.equal(bundle.authoritative, false); assert.equal(buildSbomAuditBundle({ ...links, vex: {} }).ok, false); });
console.log(`\n${passed} passed`);
