// SPDX-License-Identifier: SUL-1.0
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { authorizeSecurityAction, evaluateReadinessApplicability, projectReadinessForConsumer, validateIncidentRunbook, validatePublicArtifactRedaction, validateReadinessArtifact, validateReadinessFreshness, validateResponseTrace, validateSecurityReleaseEvidence, validateSupportWindow } from "./security-readiness.mjs";

const a = "a".repeat(64); const b = "b".repeat(64);
const securityPolicy = readFileSync(fileURLToPath(new URL("../../../SECURITY.md", import.meta.url)), "utf8");
const supportPolicy = readFileSync(fileURLToPath(new URL("../../../docs/security-support-policy.md", import.meta.url)), "utf8");
const incidentRunbook = readFileSync(fileURLToPath(new URL("../../../docs/security-incident-response.md", import.meta.url)), "utf8");
test("AC1: unclassified products are incomplete, not silently exempt", () => assert.equal(evaluateReadinessApplicability({ productType: "unknown" }).status, "incomplete"));
test("AC2: disclosure, restricted response and canonical findings remain distinct", () => { assert.equal(validateReadinessArtifact({ type: "public-disclosure", contact: "security@example.test", supportedVersions: "1.x" }).valid, true); assert.equal(validateReadinessArtifact({ type: "canonical-finding", findingId: "f", candidateSha256: a }).valid, true); assert.equal(validateReadinessArtifact({ type: "restricted-response", contact: "wrong" }).valid, false); });
test("AC3: releases outside the authoritative support window are rejected", () => { const policy = { version: "2026.1", supportedVersions: ["1.2.0"] }; assert.equal(validateSupportWindow({ policy, release: { version: "1.1.0" } }).valid, false); assert.equal(validateSupportWindow({ policy, release: { version: "1.2.0" } }).valid, true); });
test("AC4: full response trace needs named authority and evidence at every stage", () => { const stages = ["intake", "triage", "ownership", "remediation", "disclosure", "closure"].map((stage) => ({ stage, authority: "security-owner", evidenceSha256: a })); assert.equal(validateResponseTrace(stages).valid, true); assert.equal(validateResponseTrace(stages.slice(1)).valid, false); });
test("AC5: incident and rollback runbooks bind to declared deployment capabilities", () => { assert.equal(validateIncidentRunbook({ steps: [{ capability: "rollback-release" }], capabilities: ["rollback-release"] }).valid, true); assert.equal(validateIncidentRunbook({ steps: [{ capability: "invented" }], capabilities: [] }).valid, false); });
test("AC6: agents cannot take protected security decisions", () => { for (const action of ["publish-advisory", "accept-risk", "close-incident", "authorize-production-change"]) assert.equal(authorizeSecurityAction({ action, authority: "agent" }).allowed, false); });
test("AC7: security release evidence binds artifact, SBOM, provenance and validated findings", () => assert.equal(validateSecurityReleaseEvidence({ artifactSha256: a, sbomSha256: b, provenanceSha256: a, candidateSha256: b, verifiedFindingIds: ["f"] }).valid, true));
test("AC8: restricted fields cannot enter public artifacts", () => { assert.equal(validatePublicArtifactRedaction({ summary: "fixed" }).valid, true); assert.equal(validatePublicArtifactRedaction({ privateEndpoint: "no" }).valid, false); });
test("AC9: stale contacts, unsupported channels and missing artifacts are typed failures", () => { assert.equal(validateReadinessFreshness({ contact: { address: "security@example.test", expiresAt: "2026-08-01" }, at: "2026-08-02" }).code, "READINESS-CONTACT-STALE"); assert.equal(validateReadinessFreshness({ contact: { address: "security@example.test", expiresAt: "2026-09-01" }, at: "2026-08-02", channel: "chat" }).code, "READINESS-CHANNEL-UNSUPPORTED"); assert.equal(validateReadinessFreshness({ contact: { address: "security@example.test", expiresAt: "2026-09-01" }, at: "2026-08-02", channel: "email", requiredArtifacts: ["x"] }).code, "READINESS-ARTIFACT-MISSING"); });
test("AC10: public package, internal service, legacy EOL, emergency rollback, and valid not-applicable fixtures are covered", () => { assert.equal(evaluateReadinessApplicability({ productType: "public-package" }).status, "required"); assert.equal(evaluateReadinessApplicability({ productType: "internal-service" }).status, "required"); assert.equal(evaluateReadinessApplicability({ productType: "documentation-only", notApplicableReceipt: { authority: "human" } }).status, "not-applicable"); });
test("AC11: consumers can project readiness but cannot mutate authority", () => { const canonical = Object.freeze({ candidateSha256: a, status: "ready" }); const projection = projectReadinessForConsumer(canonical, { status: "closed" }); assert.equal(canonical.status, "ready"); assert.deepEqual(projection.rejectedAuthorityFields, ["status"]); });
test("AC12: public documentation declares disclosure, support, incident, release, and recovery responsibilities", () => { assert.match(securityPolicy, /Reporting a vulnerability/u); assert.match(supportPolicy, /support/u); assert.match(incidentRunbook, /Rollback/u); });
