#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
import assert from "node:assert/strict";
import { assessTrustedExecutablePath, resolveTrustedSystemExecutable } from "./trusted-tool-resolution.mjs";
let passed = 0;
function check(name, fn) { fn(); passed += 1; process.stdout.write(`PASS TTR${String(passed).padStart(2, "0")} ${name}\n`); }
const ROOT = "C:\\Windows\\System32"; const file = { isFile: () => true, isSymbolicLink: () => false }; const link = { isFile: () => false, isSymbolicLink: () => true };
function missing(path) { const error = new Error(`missing ${path}`); error.code = "ENOENT"; return error; }
function fixture(entries, realpaths = {}) { return { lstatSync(path) { const entry = entries[path]; if (entry instanceof Error) throw entry; if (!entry) throw missing(path); return entry; }, realpathSync(path) { const entry = realpaths[path] ?? path; if (entry instanceof Error) throw entry; return entry; } }; }
check("accepts a direct .exe inside a named Windows system root", () => { const path = `${ROOT}\\gitleaks.exe`; assert.deepEqual(resolveTrustedSystemExecutable("gitleaks", { platform: "win32", windowsRoots: [ROOT], fsOps: fixture({ [path]: file }) }), { ok: true, path }); });
check("accepts Git for Windows mingw64 direct executable from its named system root", () => { const root = "C:\\Program Files\\Git\\mingw64\\bin"; const path = `${root}\\git.exe`; assert.deepEqual(resolveTrustedSystemExecutable("git", { platform: "win32", windowsRoots: [root], fsOps: fixture({ [path]: file }) }), { ok: true, path }); });
check("resolves a non-Windows symlink to its regular executable target", () => { const path = "/usr/local/bin/codex"; const target = "/usr/bin/codex"; assert.deepEqual(resolveTrustedSystemExecutable("codex", { platform: "linux", fsOps: fixture({ [path]: link, [target]: file }, { [path]: target }) }), { ok: true, path: target }); });
check("rejects command, batch, and PowerShell wrappers as untrusted rather than missing", () => { for (const extension of [".cmd", ".bat", ".ps1"]) { const path = `${ROOT}\\gitleaks${extension}`; assert.deepEqual(resolveTrustedSystemExecutable("gitleaks", { platform: "win32", windowsRoots: [ROOT], fsOps: fixture({ [path]: file }) }), { ok: false, status: "untrusted_path" }); } });
check("rechecks a reparse target and rejects a user-writable final path", () => { const path = `${ROOT}\\semgrep.exe`; const userTarget = "C:\\Users\\developer\\AppData\\Local\\Temp\\semgrep.exe"; const fsOps = fixture({ [path]: link, [userTarget]: file }, { [path]: userTarget }); assert.deepEqual(resolveTrustedSystemExecutable("semgrep", { platform: "win32", windowsRoots: [ROOT], fsOps }), { ok: false, status: "untrusted_path" }); assert.deepEqual(assessTrustedExecutablePath(userTarget, { platform: "win32", windowsRoots: [ROOT], fsOps }), { ok: false, status: "untrusted_path" }); });
check("preserves probe errors separately from missing and rejected paths", () => { const denied = new Error("access denied"); denied.code = "EACCES"; assert.deepEqual(resolveTrustedSystemExecutable("osv-scanner", { platform: "win32", windowsRoots: [ROOT], fsOps: fixture({ [`${ROOT}\\osv-scanner.exe`]: denied }) }), { ok: false, status: "probe_error" }); assert.deepEqual(resolveTrustedSystemExecutable("osv-scanner", { platform: "win32", windowsRoots: [ROOT], fsOps: fixture({}) }), { ok: false, status: "binary_missing" }); });
process.stdout.write(`${passed}/6 checks passed.\n`);
