#!/usr/bin/env node
// SPDX-License-Identifier: SUL-1.0
import assert from "node:assert/strict";
import { assessTrustedExecutablePath, resolveTrustedSystemExecutable, windowsSystemToolRoots } from "./trusted-tool-resolution.mjs";
let passed = 0;
function check(name, fn) { fn(); passed += 1; process.stdout.write(`PASS TTR${String(passed).padStart(2, "0")} ${name}\n`); }
const ROOT = "C:\\Windows\\System32"; const file = { isFile: () => true, isSymbolicLink: () => false }; const link = { isFile: () => false, isSymbolicLink: () => true };
function missing(path) { const error = new Error(`missing ${path}`); error.code = "ENOENT"; return error; }
function fixture(entries, realpaths = {}) { return { lstatSync(path) { const entry = entries[path]; if (entry instanceof Error) throw entry; if (!entry) throw missing(path); return entry; }, realpathSync(path) { const entry = realpaths[path] ?? path; if (entry instanceof Error) throw entry; return entry; } }; }
check("accepts a direct .exe inside a named Windows system root", () => { const path = `${ROOT}\\gitleaks.exe`; assert.deepEqual(resolveTrustedSystemExecutable("gitleaks", { platform: "win32", windowsRoots: [ROOT], fsOps: fixture({ [path]: file }) }), { ok: true, path }); });
check("accepts Git for Windows mingw64 direct executable from its named system root", () => { const root = "C:\\Program Files\\Git\\mingw64\\bin"; const path = `${root}\\git.exe`; assert.deepEqual(resolveTrustedSystemExecutable("git", { platform: "win32", windowsRoots: [root], fsOps: fixture({ [path]: file }) }), { ok: true, path }); });
check("resolves a non-Windows symlink to its regular executable target", () => { const path = "/usr/local/bin/codex"; const target = "/usr/bin/codex"; assert.deepEqual(resolveTrustedSystemExecutable("codex", { platform: "linux", fsOps: fixture({ [path]: link, [target]: file }, { [path]: target }) }), { ok: true, path: target }); });
check("uses POSIX fixture paths for explicitly mocked Linux resolution", () => { const path = "/usr/bin/gitleaks"; assert.deepEqual(resolveTrustedSystemExecutable("gitleaks", { platform: "linux", fsOps: fixture({ [path]: file }) }), { ok: true, path }); });
check("uses the fixed Homebrew system path for explicitly mocked macOS resolution", () => { const path = "/opt/homebrew/bin/gitleaks"; assert.deepEqual(resolveTrustedSystemExecutable("gitleaks", { platform: "darwin", fsOps: fixture({ [path]: file }) }), { ok: true, path }); });
check("uses only immutable Windows roots when environment-shaped input names a caller-controlled location", () => { const env = { ProgramFiles: "D:\\caller-controlled", SystemRoot: "E:\\caller-controlled", WINDIR: "F:\\caller-controlled", USERPROFILE: "Z:\\Users\\developer" }; const attackerPath = "D:\\caller-controlled\\Git\\cmd\\gitleaks.exe"; const probes = []; const fsOps = { lstatSync(path) { probes.push(path); if (path === attackerPath) return file; throw missing(path); }, realpathSync(path) { return path; } }; assert.deepEqual(windowsSystemToolRoots(env), ["C:\\Program Files\\Git\\cmd", "C:\\Program Files\\Git\\bin", "C:\\Program Files\\Git\\mingw64\\bin", "C:\\Program Files\\Gitleaks", "C:\\Program Files\\OSV-Scanner", "C:\\Program Files\\Semgrep", "C:\\Windows\\System32", "D:\\Program Files\\Git\\cmd", "D:\\Program Files\\Git\\bin", "D:\\Program Files\\Git\\mingw64\\bin", "D:\\Dev\\Git\\Git\\cmd", "D:\\Dev\\Git\\Git\\bin", "D:\\Dev\\Git\\Git\\mingw64\\bin", "D:\\Program Files\\Gitleaks", "D:\\Program Files\\OSV-Scanner", "D:\\Program Files\\Semgrep", "D:\\Windows\\System32"]); assert.equal(Object.isFrozen(windowsSystemToolRoots()), true); assert.deepEqual(resolveTrustedSystemExecutable("gitleaks", { platform: "win32", env, fsOps }), { ok: false, status: "binary_missing" }); assert.equal(probes.includes(attackerPath), false); });
check("accepts a direct scanner executable from the immutable D drive system root", () => { const root = "D:\\Program Files\\Gitleaks"; const path = `${root}\\gitleaks.exe`; assert.deepEqual(resolveTrustedSystemExecutable("gitleaks", { platform: "win32", fsOps: fixture({ [path]: file }) }), { ok: true, path }); });
check("does not search user paths and still rejects wrappers in named Windows roots", () => { const userPath = "Z:\\Users\\developer\\gitleaks.exe"; const denied = new Error("user path touched"); denied.code = "EACCES"; const noUserSearch = { lstatSync(path) { if (path === userPath) throw denied; throw missing(path); }, realpathSync(path) { return path; } }; assert.deepEqual(resolveTrustedSystemExecutable("gitleaks", { platform: "win32", fsOps: noUserSearch }), { ok: false, status: "binary_missing" }); const wrapper = "C:\\Program Files\\Git\\cmd\\gitleaks.cmd"; assert.deepEqual(resolveTrustedSystemExecutable("gitleaks", { platform: "win32", fsOps: fixture({ [wrapper]: file }) }), { ok: false, status: "untrusted_path" }); });
check("rejects command, batch, and PowerShell wrappers as untrusted rather than missing", () => { for (const extension of [".cmd", ".bat", ".ps1"]) { const path = `${ROOT}\\gitleaks${extension}`; assert.deepEqual(resolveTrustedSystemExecutable("gitleaks", { platform: "win32", windowsRoots: [ROOT], fsOps: fixture({ [path]: file }) }), { ok: false, status: "untrusted_path" }); } });
check("rechecks a reparse target and rejects a user-writable final path", () => { const path = `${ROOT}\\semgrep.exe`; const userTarget = "C:\\Users\\developer\\AppData\\Local\\Temp\\semgrep.exe"; const fsOps = fixture({ [path]: link, [userTarget]: file }, { [path]: userTarget }); assert.deepEqual(resolveTrustedSystemExecutable("semgrep", { platform: "win32", windowsRoots: [ROOT], fsOps }), { ok: false, status: "untrusted_path" }); assert.deepEqual(assessTrustedExecutablePath(userTarget, { platform: "win32", windowsRoots: [ROOT], fsOps }), { ok: false, status: "untrusted_path" }); });
check("preserves probe errors separately from missing and rejected paths", () => { const denied = new Error("access denied"); denied.code = "EACCES"; assert.deepEqual(resolveTrustedSystemExecutable("osv-scanner", { platform: "win32", windowsRoots: [ROOT], fsOps: fixture({ [`${ROOT}\\osv-scanner.exe`]: denied }) }), { ok: false, status: "probe_error" }); assert.deepEqual(resolveTrustedSystemExecutable("osv-scanner", { platform: "win32", windowsRoots: [ROOT], fsOps: fixture({}) }), { ok: false, status: "binary_missing" }); });
check("accepts this host's PO-approved D:\\Dev\\Git\\Git direct executable from its named root", () => { const root = "D:\\Dev\\Git\\Git\\mingw64\\bin"; const path = `${root}\\git.exe`; assert.deepEqual(resolveTrustedSystemExecutable("git", { platform: "win32", windowsRoots: [root], fsOps: fixture({ [path]: file }) }), { ok: true, path }); });
check("still rejects a wrapper inside the D:\\Dev\\Git\\Git host-approved root", () => { const root = "D:\\Dev\\Git\\Git\\cmd"; const path = `${root}\\git.bat`; assert.deepEqual(resolveTrustedSystemExecutable("git", { platform: "win32", windowsRoots: [root], fsOps: fixture({ [path]: file }) }), { ok: false, status: "untrusted_path" }); });
check("still rejects a neighboring sibling directory outside the exact D:\\Dev\\Git\\Git root", () => { const path = "D:\\Dev\\Git\\Git-other\\cmd\\git.exe"; assert.deepEqual(resolveTrustedSystemExecutable("git", { platform: "win32", windowsRoots: ["D:\\Dev\\Git\\Git\\cmd"], fsOps: fixture({ [path]: file }) }), { ok: false, status: "binary_missing" }); });
if (process.platform === "win32") {
  check("resolves this host's real, PO-approved Git install natively (no mocks)", () => { const resolved = resolveTrustedSystemExecutable("git"); assert.equal(resolved.ok, true, JSON.stringify(resolved)); assert.match(resolved.path.toLowerCase(), /^d:\\dev\\git\\git\\(cmd|bin|mingw64\\bin)\\git\.exe$/); });
}
process.stdout.write(`${passed}/${passed} checks passed.\n`);
