// SPDX-License-Identifier: SUL-1.0
import assert from "node:assert/strict";
import test from "node:test";
import { main } from "./change-control.mjs";
const candidate = { commit: "a".repeat(40), tree: "b".repeat(40) }; const artifact = { path: "specs/release/result.md", sha256: "c".repeat(64) };
const profile = { candidate, artifact, environment: "production" };
const humanAuthority = { granted: true, scope: { candidate, artifact, environment: "production", action: "APPROVE_DEPLOY", artifacts: [artifact] } };
test("loads explicit gate inputs, preserves an absent external receipt, and independently requires a bound ledger authority", async () => { const loaded = []; const authorityCalls = []; const result = await main(["gate", "--repo", "repo", "--profile-file", "profile.json", "--pipeline-authority-file", "authority.json", "--authority-request-file", "ledger.json", "--external-receipt-file", "none", "--now-ms", "1"], { readJson: async (path) => { loaded.push(path); return path === "profile.json" ? profile : { path }; }, readAuthority: async (args) => { authorityCalls.push(args); return humanAuthority; }, evaluate: (input) => ({ status: "blocked", external: input.externalReceipt, now: input.nowEpochMs }) }); assert.deepEqual(loaded, ["profile.json", "authority.json"]); assert.deepEqual(authorityCalls, [["--repo", "repo", "--request-file", "ledger.json"]]); assert.deepEqual(result, { status: "blocked", external: null, now: 1 }); });
test("fails closed before evaluating legacy pipeline authority when the ledger scope is absent or mismatched", async () => { const result = await main(["gate", "--repo", "repo", "--profile-file", "profile.json", "--pipeline-authority-file", "authority.json", "--authority-request-file", "ledger.json", "--external-receipt-file", "none", "--now-ms", "1"], { readJson: async (path) => path === "profile.json" ? profile : {}, readAuthority: async () => ({ granted: true, scope: { ...humanAuthority.scope, action: "APPROVE_PUSH" } }), evaluate: () => { throw new Error("must not evaluate legacy projection"); } }); assert.deepEqual(result, { schema: "pipeline.change-control-gate.v1", status: "blocked", reason: "human-authority" }); });
test("rejects malformed argument layouts before reading files", async () => { await assert.rejects(() => main(["gate", "--profile-file", "one"]), (error) => error.code === "CCC-ARGUMENT"); });
