// SPDX-License-Identifier: SUL-1.0
import assert from "node:assert/strict";
import { hasObservedReadOnlyCapability, validateForgeCapabilityReport } from "../lib/forge-capability.mjs";
import { mapGitHubAdapterObservation, resolveGitHubTarget } from "./github-forge-adapter.mjs";
const A = "a".repeat(64); const evidence = (kind) => [{ kind, path: null, fileSha256: A, recordSha256: null }];
const cell = (mode = "native", status = "observed") => ({ mode, status, evidence: status === "observed" ? evidence("synthetic-readback") : [] });
const observation = (target) => mapGitHubAdapterObservation({ reportId: "nova-b4-github", target, observations: { actionsJobsRead: cell(), actionsPipelinesRead: cell(), actionsPipelinesRetry: cell("unavailable", "unavailable"), branchProtectionRead: cell("emulated"), issuesRead: cell(), issuesWrite: cell("unsupported", "unsupported"), pullRequestsRead: cell(), pullRequestsWrite: cell("unsupported", "unsupported") }, governance: [{ controlId: "tier", mode: "manual", status: "not-observed", tier: "unknown", evidence: [] }], evidence: evidence("fixture") });
const check = (name, fn) => { try { fn(); process.stdout.write(`PASS ${name}\n`); } catch (e) { process.stderr.write(`FAIL ${name}: ${e.stack}\n`); process.exitCode = 1; } };
check("GitHub target binds exactly github.com and explicit project coordinates", () => { const result = resolveGitHubTarget({ baseUrl: "https://github.com", projectPath: "agent-pipe-shared/agent-pipeline", authenticationMode: "operator-local" }); assert.equal(result.ok, true); assert.equal(result.target.baseUrlClass, "github-com"); assert.equal(Object.hasOwn(result.target, "token"), false); });
check("ambiguous hosts, paths, and credential-shaped input fail closed", () => { for (const baseUrl of ["http://github.com", "https://github.com/", "https://github.enterprise"]) assert.equal(resolveGitHubTarget({ baseUrl, projectPath: "owner/repo", authenticationMode: "none" }).ok, false); assert.equal(resolveGitHubTarget({ baseUrl: "https://github.com", projectPath: "owner/repo", authenticationMode: "none", token: "no" }).ok, false); });
check("closed GitHub extension maps provider names out of the neutral capability report", () => { const target = resolveGitHubTarget({ baseUrl: "https://github.com", projectPath: "owner/repo", authenticationMode: "none" }).target; const report = observation(target); assert.deepEqual(validateForgeCapabilityReport(report), { ok: true, code: null }); assert.equal(hasObservedReadOnlyCapability(report), true); assert.doesNotMatch(JSON.stringify(report.cells), /github|pull-request|actions/iu); });
check("raw provider response fields never cross the adapter boundary", () => { const target = resolveGitHubTarget({ baseUrl: "https://github.com", projectPath: "owner/repo", authenticationMode: "none" }).target; assert.throws(() => mapGitHubAdapterObservation({ ...{ reportId: "x", target, observations: {}, governance: [], evidence: [] }, rawResponse: {} }), /SHAPE/u); });
