// SPDX-License-Identifier: SUL-1.0
import assert from "node:assert/strict";
import test from "node:test";
import { buildGovernanceActionEvent } from "../lib/governance-action-events.mjs";
import { main } from "./governance-replay.mjs";
const candidate = { commit: "a".repeat(40), tree: "b".repeat(40) };
const checkpoint = { repositoryFingerprint: "a".repeat(64), streamId: "lifecycle", sequence: 2, eventDigest: "2".repeat(64), candidateCommit: candidate.commit, candidateTree: candidate.tree };
function event(sequence) { return { sequence, eventDigest: String(sequence).repeat(64), occurredAtEpochMs: sequence, candidate, payloadSchema: "pipeline.lifecycle-governance-event.v1", payload: { eventId: `event-${sequence}`, kind: "dispatch", status: "active", reasonCode: "DISPATCHED", correlation: { packageId: "phoenix-3", dispatchId: "dispatch-1", attemptId: "attempt-1", workerId: "worker-1", correlationId: "correlation-1", queueRevision: 0 }, candidate, invalidatesEventId: null, supersedesEventId: null } }; }
function action(sequence) { return { sequence, eventDigest: String(sequence).repeat(64), occurredAtEpochMs: sequence, candidate, payloadSchema: "pipeline.governance-action-event.v1", payload: buildGovernanceActionEvent({ kind: "verification", status: "completed", reasonCode: "VERIFICATION_PASSED", requestId: `verify-${sequence}`, featureId: { state: "not-applicable" }, sessionId: { state: "not-applicable" }, candidate }) }; }
test("projects only a verified mixed lifecycle stream through the v2 non-authoritative replay boundary", async () => { const result = await main(["--repo", "/repo", "--repository-fingerprint", "a".repeat(64)], { query: async () => ({ completeness: "verified", integrity: "valid", checkpoint, events: [event(1), action(2)] }) }); assert.equal(result.schema, "pipeline.governance-replay-readback.v2"); assert.equal(result.status, "observed"); assert.equal(result.dispatchTimelines[0].authority, "non-authoritative"); assert.equal(result.actionTimelines.length, 1); });
test("does not project an incomplete or invalid canonical stream", async () => { const result = await main(["--repo", "/repo", "--repository-fingerprint", "a".repeat(64)], { query: async () => ({ completeness: "unknown", integrity: "prefix-valid", events: [event(1)] }) }); assert.equal(result.status, "unavailable"); assert.equal(result.dispatchTimelines.length, 0); assert.equal(result.actionTimelines.length, 0); });
test("rejects a verified result with an incomplete checkpoint", async () => { await assert.rejects(main(["--repo", "/repo", "--repository-fingerprint", "a".repeat(64)], { query: async () => ({ completeness: "verified", integrity: "valid", checkpoint: { sequence: 1 }, events: [event(1)] }) }), (error) => error.code === "GRC-CHECKPOINT"); });
