#!/usr/bin/env node
// SPDX-License-Identifier: SUL-1.0
/** Read-only policy inspection and authority-bound activation planning CLI. */
import { readFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";
import { parseStrictJson } from "../lib/governance-event.mjs";
import { resolveEffectiveOrganizationPolicy } from "../lib/organization-policy.mjs";
import { planOrganizationPolicyActivation } from "../lib/organization-policy-activation.mjs";
function fail(code, message) { const error = new Error(message); error.code = code; throw error; }
function parse(argv) { if (!new Set(["inspect", "plan"]).has(argv[0]) || (argv.length - 1) % 2 !== 0) fail("OPC-ARGUMENT", "Usage: organization-policy.mjs inspect|plan --core-version <semver> --pack-file <json>… [--repo <checkout> --activation-id <id>]"); const sub = argv[0]; const flags = new Map(); for (let index = 1; index < argv.length; index += 2) { const key = argv[index]; const value = argv[index + 1]; if (!["--repo", "--core-version", "--pack-file", "--activation-id"].includes(key) || value === undefined || (key !== "--pack-file" && flags.has(key))) fail("OPC-ARGUMENT", "Organization policy arguments are invalid."); const list = flags.get(key) ?? []; flags.set(key, [...list, value]); } const coreVersion = flags.get("--core-version")?.[0]; const packs = flags.get("--pack-file") ?? []; if (!coreVersion || packs.length === 0) fail("OPC-ARGUMENT", "Core version and at least one pack are required."); if (sub === "inspect" && (flags.has("--repo") || flags.has("--activation-id"))) fail("OPC-ARGUMENT", "inspect accepts no activation options."); if (sub === "plan" && (!flags.get("--repo")?.[0] || !flags.get("--activation-id")?.[0])) fail("OPC-ARGUMENT", "plan requires repo and activation id."); return { sub, coreVersion, packFiles: packs, repositoryRoot: flags.get("--repo")?.[0] ?? null, activationId: flags.get("--activation-id")?.[0] ?? null }; }
async function readJson(path, read = readFile) { try { return parseStrictJson(await read(path)); } catch { fail("OPC-JSON", "A policy pack JSON input is invalid."); } }
export async function main(argv = process.argv.slice(2), deps = {}) { const options = parse(argv); const load = deps.readJson ?? readJson; const packs = []; for (const path of options.packFiles) packs.push(await load(path)); if (options.sub === "inspect") return (deps.resolve ?? resolveEffectiveOrganizationPolicy)({ coreVersion: options.coreVersion, packs }); return (deps.plan ?? planOrganizationPolicyActivation)({ repositoryRoot: options.repositoryRoot, coreVersion: options.coreVersion, packs, activationId: options.activationId }); }
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) { try { process.stdout.write(`${JSON.stringify(await main())}\n`); } catch (error) { process.stderr.write(`${error.code ?? "OPC-FAILED"}: ${error.message}\n`); process.exitCode = 2; } }
