#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
import assert from "node:assert/strict";
import { existsSync, mkdtempSync, rmSync, statSync, unlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createHash } from "node:crypto";
import { approvePublication, authorizePublication, closePublication, observePublication, preparePublication, publicationDigest, startReadback } from "../lib/publication-bundle.mjs";
import { advanceCloseJournal, createCloseJournal, createPublicationLifecycle, importPublicationChannel, lifecycleDigest, publicationClosePaths, readCloseJournal, readPublicationLifecycle, recordCleanup, storeCloseJournal, storePublicationLifecycle } from "./publication-close-journal.mjs";
const h = (char, length = 64) => char.repeat(length);
const rawDigest = (value) => createHash("sha256").update(`${JSON.stringify(value, null, 2)}\n`).digest("hex");
const authority = { implementationResultDigest: h("1"), prdDigest: h("2"), specDigests: [h("3"), h("4"), h("5"), h("6"), h("7"), h("8")], verifyDigest: h("9"), criticDigest: h("a"), d2ReceiptDigest: h("b"), privateIntentDigest: h("c"), publicIntentDigest: h("d") };
const prerequisite = { d2: { phase: "verified", receiptDigest: h("b"), closePostimageDigest: h("e") }, closePostimageDigest: h("e"), afk: { status: "complete", receiptDigest: h("f") }, recoveryPending: false };
const evidence = (char, oid, tree) => ({ path: `evidence/${char}.json`, rawDigest: h(char), commit: oid, tree });
function receipt(channel, char) {
  const oid = h(char, 40), tree = h(char === "1" ? "2" : "4", 40), preimage = h("0", 40);
  let state = preparePublication({ channel, transactionId: `${channel}-1`, repositoryFingerprint: h("1"), sourceCommit: h("8", 40), sourceTree: h("9", 40), remoteFingerprint: h("2"), remoteName: "origin", destinationRef: "refs/heads/main", remotePreimageOid: preimage, candidateOid: oid, candidateTree: tree, ancestry: { baseOid: preimage, candidateOid: oid, descends: true }, identityProbe: evidence("3", oid, tree), verifyEvidence: evidence("4", oid, tree), securityEvidence: evidence("5", oid, tree), ...(channel === "neutral-public" ? { neutralEvidence: { planDigest: h("6"), reviewDigest: h("7"), leakageDigest: h("8"), metadataDigest: h("9"), endpointProbeDigest: h("a"), candidateCommit: oid, candidateTree: tree } } : {}) });
  state = approvePublication(state, { expectedRevision: 0, expectedStateSha256: publicationDigest(state), approvalId: `${channel}-approval`, attribution: "PO", approvedAt: 1, expiresAt: 2 });
  state = authorizePublication(state, { expectedRevision: 1, expectedStateSha256: publicationDigest(state), now: 2, command: ["git", "push", "--porcelain", "origin", `${oid}:refs/heads/main`] });
  state = observePublication(state, { expectedRevision: 2, expectedStateSha256: publicationDigest(state), observedOid: oid, observedAt: 3, status: "observed" });
  state = startReadback(state, { expectedRevision: 3, expectedStateSha256: publicationDigest(state), repositoryKind: "fresh-disposable", alternatesDisabled: true, destinationRef: "refs/heads/main" });
  return closePublication(state, { expectedRevision: 4, expectedStateSha256: publicationDigest(state), fetchedRef: "refs/heads/main", fetchedOid: oid, fetchedTree: tree, completedAt: 4 });
}
let tests = 0; const check = (name, fn) => { fn(); tests++; };
let journal = createCloseJournal({ lifecycleId: "batman", candidateOid: h("a", 40), candidateTree: h("b", 40), authority, afkComplete: true, recoveryPending: false });
const common = mkdtempSync(join(tmpdir(), "publication-close-"));
const initial = storeCloseJournal({ gitCommonDir: common, journal, expectedRawSha256: null });
journal = advanceCloseJournal(journal, { expectedRevision: 0, expectedStateSha256: lifecycleDigest(journal), phase: "implementation-result-bound", inputDigest: h("c"), observedDigest: h("d") });
check("ordered close phase", () => assert.equal(journal.phase, "implementation-result-bound"));
check("identical phase replay is zero-state-change", () => assert.equal(advanceCloseJournal(journal, { expectedRevision: 1, expectedStateSha256: lifecycleDigest(journal), phase: "implementation-result-bound", inputDigest: h("c"), observedDigest: h("d") }), journal));
check("conflicting replay blocks", () => assert.throws(() => advanceCloseJournal(journal, { expectedRevision: 1, expectedStateSha256: lifecycleDigest(journal), phase: "implementation-result-bound", inputDigest: h("e"), observedDigest: h("d") }), /conflicting/));
const first = storeCloseJournal({ gitCommonDir: common, journal, expectedRawSha256: initial.rawDigest });
check("durable journal is mode 0600", () => assert.equal(statSync(first.path).mode & 0o777, 0o600));
const before = statSync(first.path).mtimeMs;
const replayStore = storeCloseJournal({ gitCommonDir: common, journal, expectedRawSha256: first.rawDigest });
check("identical durable replay does not replace journal", () => { assert.equal(replayStore.written, false); assert.equal(statSync(first.path).mtimeMs, before); });
check("stale raw CAS blocks", () => assert.throws(() => storeCloseJournal({ gitCommonDir: common, journal, expectedRawSha256: h("0") }), /stale/));
check("recovery names only next phase", () => assert.equal(readCloseJournal(common, "batman").nextPhase, "feature-closed"));
const lockPath = publicationClosePaths(common, "batman").lock;
writeFileSync(lockPath, "foreign-lock\n", { mode: 0o600 });
check("foreign writer lock is never removed", () => { assert.throws(() => storeCloseJournal({ gitCommonDir: common, journal, expectedRawSha256: first.rawDigest }), /EEXIST/); assert.equal(existsSync(lockPath), true); });
unlinkSync(lockPath);
writeFileSync(first.path, "torn\n", { mode: 0o600 });
check("torn state blocks recovery", () => assert.throws(() => readCloseJournal(common, "batman"), /torn/));
rmSync(common, { recursive: true, force: true });
let lifecycle = createPublicationLifecycle({ lifecycleId: "batman", epicId: "epic", featureId: "feature", prerequisites: prerequisite });
const lifecycleCommon = mkdtempSync(join(tmpdir(), "publication-lifecycle-"));
let storedLifecycle = storePublicationLifecycle({ gitCommonDir: lifecycleCommon, lifecycle, expectedRawSha256: null });
check("aggregate lifecycle is durable mode 0600", () => { assert.equal(statSync(storedLifecycle.path).mode & 0o777, 0o600); assert.equal(readPublicationLifecycle(lifecycleCommon, "batman").lifecycle.status, "preparing"); });
const privateReceipt = receipt("private", "1");
const importArgs = (channel, value, completedAt) => {
  const receiptRawBytes = `${JSON.stringify(value, null, 2)}\n`;
  return { expectedRevision: lifecycle.revision, expectedStateSha256: lifecycleDigest(lifecycle), channel, receipt: value, receiptRawBytes, receiptRawDigest: rawDigest(value), receiptLocator: `publication/${channel}.json`, observation: { path: `publication/${channel}-readback.json`, rawDigest: h(channel === "private" ? "9" : "a"), endpointFingerprint: value.remoteFingerprint, ref: value.destinationRef, oid: value.candidateOid, tree: value.candidateTree, observedAt: completedAt } };
};
lifecycle = importPublicationChannel(lifecycle, importArgs("private", privateReceipt, 10));
storedLifecycle = storePublicationLifecycle({ gitCommonDir: lifecycleCommon, lifecycle, expectedRawSha256: storedLifecycle.rawDigest });
check("private import advances only private", () => { assert.equal(lifecycle.status, "private-complete"); assert.equal(lifecycle.channels["neutral-public"], null); });
const publicReceipt = receipt("neutral-public", "3");
lifecycle = importPublicationChannel(lifecycle, importArgs("neutral-public", publicReceipt, 11));
storedLifecycle = storePublicationLifecycle({ gitCommonDir: lifecycleCommon, lifecycle, expectedRawSha256: storedLifecycle.rawDigest });
check("both exact typed readbacks derive complete", () => assert.equal(lifecycle.status, "complete"));
const replayLifecycle = importPublicationChannel(lifecycle, { ...importArgs("private", privateReceipt, 10), expectedRevision: lifecycle.revision, expectedStateSha256: lifecycleDigest(lifecycle) });
check("identical channel replay is zero-state-change", () => assert.equal(replayLifecycle, lifecycle));
check("receipt raw digest is recomputed", () => assert.throws(() => importPublicationChannel(createPublicationLifecycle({ lifecycleId: "x", epicId: "epic", featureId: "feature", prerequisites: prerequisite }), { ...importArgs("private", privateReceipt, 10), expectedRevision: 0, expectedStateSha256: lifecycleDigest(createPublicationLifecycle({ lifecycleId: "x", epicId: "epic", featureId: "feature", prerequisites: prerequisite })), receiptRawDigest: h("0") }), /raw digest/));
lifecycle = recordCleanup(lifecycle, { expectedRevision: 2, expectedStateSha256: lifecycleDigest(lifecycle), status: "uncertain", evidenceDigest: h("f") });
storedLifecycle = storePublicationLifecycle({ gitCommonDir: lifecycleCommon, lifecycle, expectedRawSha256: storedLifecycle.rawDigest });
check("cleanup uncertainty blocks without erasing receipts", () => { assert.equal(lifecycle.status, "blocked"); assert.notEqual(lifecycle.channels.private, null); });
rmSync(lifecycleCommon, { recursive: true, force: true });
console.log(`publication-close-journal: ${tests} tests passed`);
