// SPDX-License-Identifier: SUL-1.0
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, mkdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { createHash } from "node:crypto";
const root = resolve(new URL("../../..", import.meta.url).pathname); const cli = join(root, "plugins/pipeline-core/scripts/sbom-discovery.mjs"); const sha = (value) => createHash("sha256").update(value).digest("hex"); let passed = 0;
function test(name, fn) { try { fn(); passed += 1; console.log(`PASS ${name}`); } catch (error) { console.error(`FAIL ${name}: ${error.message}`); process.exitCode = 1; } }
const candidate = { repositoryFingerprint: "f".repeat(64), commit: "a".repeat(40), tree: "b".repeat(40) };
function canonicalSbom() { const digest = (character) => character.repeat(64); return { schema: "pipeline.sbom-manifest.v1", candidate, sourceInputs: [{ path: "package-lock.json", sha256: digest("c") }], adapter: { id: "node-reference", version: "1", configSha256: digest("d") }, formats: [{ format: "cyclonedx-json", profile: "CycloneDX-1.6", payloadSha256: digest("e") }, { format: "spdx-json", profile: "SPDX-2.3", payloadSha256: digest("f") }], components: [], completeness: { status: "complete", declared: 0, observed: 0 }, freshness: { status: "fresh", candidateMatches: true, sourceInputsMatch: true }, privacy: { classification: "private", exportPolicy: "private-only" }, payload: { canonicalSha256: digest("0"), formats: { "cyclonedx-json": { profile: "CycloneDX-1.6", sha256: digest("e") }, "spdx-json": { profile: "SPDX-2.3", sha256: digest("f") } } }, lifecycle: { state: "complete", code: "SBOM-COMPLETE" } }; }
function fixture(dir, path) { mkdirSync(join(dir, "specs/f", path.split("/").slice(0, -1).join("/")), { recursive: true }); writeFileSync(join(dir, "specs/f/prd.md"), "prd"); const bytes = `${JSON.stringify(canonicalSbom())}\n`; writeFileSync(join(dir, `specs/f/${path}`), bytes); const manifest = { schema: "pipeline.feature-package.v1", feature: { id: "f", rigor: 1 }, state: "draft", candidate: { commit: candidate.commit, tree: candidate.tree }, supersedes: null, artifacts: [{ class: "prd", path: "specs/f/prd.md", sha256: sha("prd"), authority: true, mutability: "mutable", retention: "active" }, { class: "supply-chain", path: `specs/f/${path}`, sha256: sha(bytes), authority: false, mutability: "immutable", retention: "retain" }] }; writeFileSync(join(dir, "specs/f/lifecycle.json"), JSON.stringify(manifest)); }
test("one command resolves two layouts without path guessing", () => { const first = mkdtempSync(join(tmpdir(), "sbom-cli-one-")); const second = mkdtempSync(join(tmpdir(), "sbom-cli-two-")); fixture(first, "out/bom.json"); fixture(second, "elsewhere/bom.json"); const run = (dir) => JSON.parse(execFileSync(process.execPath, [cli, "--root", dir], { encoding: "utf8" })); assert.equal(run(first).artifact.path, "specs/f/out/bom.json"); assert.equal(run(second).artifact.path, "specs/f/elsewhere/bom.json"); });
test("migration preview remains a typed zero-write command", () => { const dir = mkdtempSync(join(tmpdir(), "sbom-cli-legacy-")); mkdirSync(join(dir, "specs")); const result = JSON.parse(execFileSync(process.execPath, [cli, "--root", dir, "--migration-preview"], { encoding: "utf8" })); assert.deepEqual(result.writes, []); });
console.log(`\n${passed} passed`);
